/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AcceptContract200ApplicationJSON - OK
 */
public class AcceptContract200ApplicationJSON {
    @JsonProperty("data")
    public AcceptContract200ApplicationJSONData data;

    public AcceptContract200ApplicationJSON withData(AcceptContract200ApplicationJSONData data) {
        this.data = data;
        return this;
    }
    
    public AcceptContract200ApplicationJSON(@JsonProperty("data") AcceptContract200ApplicationJSONData data) {
        this.data = data;
  }
}
