/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class AcceptContractResponse {
    
    public String contentType;

    public AcceptContractResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public AcceptContractResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public AcceptContractResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public AcceptContract200ApplicationJSON acceptContract200ApplicationJSONObject;

    public AcceptContractResponse withAcceptContract200ApplicationJSONObject(AcceptContract200ApplicationJSON acceptContract200ApplicationJSONObject) {
        this.acceptContract200ApplicationJSONObject = acceptContract200ApplicationJSONObject;
        return this;
    }
    
    public AcceptContractResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
