/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import emdash.SpaceTraders.utils.SpeakeasyMetadata;

public class AcceptContractRequest {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=contractId")
    public String contractId;

    public AcceptContractRequest withContractId(String contractId) {
        this.contractId = contractId;
        return this;
    }
    
    public AcceptContractRequest(@JsonProperty("contractId") String contractId) {
        this.contractId = contractId;
  }
}
