/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class CreateChartResponse {
    
    public String contentType;

    public CreateChartResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public CreateChartResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public CreateChartResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Created
     */
    
    public CreateChart201ApplicationJSON createChart201ApplicationJSONObject;

    public CreateChartResponse withCreateChart201ApplicationJSONObject(CreateChart201ApplicationJSON createChart201ApplicationJSONObject) {
        this.createChart201ApplicationJSONObject = createChart201ApplicationJSONObject;
        return this;
    }
    
    public CreateChartResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
