/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class CreateShipWaypointScan201ApplicationJSONData {
    /**
     * A cooldown is a period of time in which a ship cannot perform certain actions.
     */
    @JsonProperty("cooldown")
    public emdash.SpaceTraders.models.shared.Cooldown cooldown;

    public CreateShipWaypointScan201ApplicationJSONData withCooldown(emdash.SpaceTraders.models.shared.Cooldown cooldown) {
        this.cooldown = cooldown;
        return this;
    }
    
    @JsonProperty("waypoints")
    public emdash.SpaceTraders.models.shared.ScannedWaypoint[] waypoints;

    public CreateShipWaypointScan201ApplicationJSONData withWaypoints(emdash.SpaceTraders.models.shared.ScannedWaypoint[] waypoints) {
        this.waypoints = waypoints;
        return this;
    }
    
    public CreateShipWaypointScan201ApplicationJSONData(@JsonProperty("cooldown") emdash.SpaceTraders.models.shared.Cooldown cooldown, @JsonProperty("waypoints") emdash.SpaceTraders.models.shared.ScannedWaypoint[] waypoints) {
        this.cooldown = cooldown;
        this.waypoints = waypoints;
  }
}
