/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class CreateChart201ApplicationJSONData {
    /**
     * The chart of a system or waypoint, which makes the location visible to other agents.
     */
    @JsonProperty("chart")
    public emdash.SpaceTraders.models.shared.Chart chart;

    public CreateChart201ApplicationJSONData withChart(emdash.SpaceTraders.models.shared.Chart chart) {
        this.chart = chart;
        return this;
    }
    
    /**
     * A waypoint is a location that ships can travel to such as a Planet, Moon or Space Station.
     */
    @JsonProperty("waypoint")
    public emdash.SpaceTraders.models.shared.Waypoint waypoint;

    public CreateChart201ApplicationJSONData withWaypoint(emdash.SpaceTraders.models.shared.Waypoint waypoint) {
        this.waypoint = waypoint;
        return this;
    }
    
    public CreateChart201ApplicationJSONData(@JsonProperty("chart") emdash.SpaceTraders.models.shared.Chart chart, @JsonProperty("waypoint") emdash.SpaceTraders.models.shared.Waypoint waypoint) {
        this.chart = chart;
        this.waypoint = waypoint;
  }
}
