/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreateSurvey201ApplicationJSON - Created
 */
public class CreateSurvey201ApplicationJSON {
    @JsonProperty("data")
    public CreateSurvey201ApplicationJSONData data;

    public CreateSurvey201ApplicationJSON withData(CreateSurvey201ApplicationJSONData data) {
        this.data = data;
        return this;
    }
    
    public CreateSurvey201ApplicationJSON(@JsonProperty("data") CreateSurvey201ApplicationJSONData data) {
        this.data = data;
  }
}
