/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreateShipSystemScan201ApplicationJSON - Created
 */
public class CreateShipSystemScan201ApplicationJSON {
    @JsonProperty("data")
    public CreateShipSystemScan201ApplicationJSONData data;

    public CreateShipSystemScan201ApplicationJSON withData(CreateShipSystemScan201ApplicationJSONData data) {
        this.data = data;
        return this;
    }
    
    public CreateShipSystemScan201ApplicationJSON(@JsonProperty("data") CreateShipSystemScan201ApplicationJSONData data) {
        this.data = data;
  }
}
