/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class CreateShipWaypointScanResponse {
    
    public String contentType;

    public CreateShipWaypointScanResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public CreateShipWaypointScanResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public CreateShipWaypointScanResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Created
     */
    
    public CreateShipWaypointScan201ApplicationJSON createShipWaypointScan201ApplicationJSONObject;

    public CreateShipWaypointScanResponse withCreateShipWaypointScan201ApplicationJSONObject(CreateShipWaypointScan201ApplicationJSON createShipWaypointScan201ApplicationJSONObject) {
        this.createShipWaypointScan201ApplicationJSONObject = createShipWaypointScan201ApplicationJSONObject;
        return this;
    }
    
    public CreateShipWaypointScanResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
