/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class CreateShipShipScanResponse {
    
    public String contentType;

    public CreateShipShipScanResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public CreateShipShipScanResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public CreateShipShipScanResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Created
     */
    
    public CreateShipShipScan201ApplicationJSON createShipShipScan201ApplicationJSONObject;

    public CreateShipShipScanResponse withCreateShipShipScan201ApplicationJSONObject(CreateShipShipScan201ApplicationJSON createShipShipScan201ApplicationJSONObject) {
        this.createShipShipScan201ApplicationJSONObject = createShipShipScan201ApplicationJSONObject;
        return this;
    }
    
    public CreateShipShipScanResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
