/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class CreateShipShipScan201ApplicationJSONData {
    /**
     * A cooldown is a period of time in which a ship cannot perform certain actions.
     */
    @JsonProperty("cooldown")
    public emdash.SpaceTraders.models.shared.Cooldown cooldown;

    public CreateShipShipScan201ApplicationJSONData withCooldown(emdash.SpaceTraders.models.shared.Cooldown cooldown) {
        this.cooldown = cooldown;
        return this;
    }
    
    @JsonProperty("ships")
    public emdash.SpaceTraders.models.shared.ScannedShip[] ships;

    public CreateShipShipScan201ApplicationJSONData withShips(emdash.SpaceTraders.models.shared.ScannedShip[] ships) {
        this.ships = ships;
        return this;
    }
    
    public CreateShipShipScan201ApplicationJSONData(@JsonProperty("cooldown") emdash.SpaceTraders.models.shared.Cooldown cooldown, @JsonProperty("ships") emdash.SpaceTraders.models.shared.ScannedShip[] ships) {
        this.cooldown = cooldown;
        this.ships = ships;
  }
}
