/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class CreateSurvey201ApplicationJSONData {
    /**
     * A cooldown is a period of time in which a ship cannot perform certain actions.
     */
    @JsonProperty("cooldown")
    public emdash.SpaceTraders.models.shared.Cooldown cooldown;

    public CreateSurvey201ApplicationJSONData withCooldown(emdash.SpaceTraders.models.shared.Cooldown cooldown) {
        this.cooldown = cooldown;
        return this;
    }
    
    @JsonProperty("surveys")
    public emdash.SpaceTraders.models.shared.Survey[] surveys;

    public CreateSurvey201ApplicationJSONData withSurveys(emdash.SpaceTraders.models.shared.Survey[] surveys) {
        this.surveys = surveys;
        return this;
    }
    
    public CreateSurvey201ApplicationJSONData(@JsonProperty("cooldown") emdash.SpaceTraders.models.shared.Cooldown cooldown, @JsonProperty("surveys") emdash.SpaceTraders.models.shared.Survey[] surveys) {
        this.cooldown = cooldown;
        this.surveys = surveys;
  }
}
