/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class CreateShipSystemScan201ApplicationJSONData {
    /**
     * A cooldown is a period of time in which a ship cannot perform certain actions.
     */
    @JsonProperty("cooldown")
    public emdash.SpaceTraders.models.shared.Cooldown cooldown;

    public CreateShipSystemScan201ApplicationJSONData withCooldown(emdash.SpaceTraders.models.shared.Cooldown cooldown) {
        this.cooldown = cooldown;
        return this;
    }
    
    @JsonProperty("systems")
    public emdash.SpaceTraders.models.shared.ScannedSystem[] systems;

    public CreateShipSystemScan201ApplicationJSONData withSystems(emdash.SpaceTraders.models.shared.ScannedSystem[] systems) {
        this.systems = systems;
        return this;
    }
    
    public CreateShipSystemScan201ApplicationJSONData(@JsonProperty("cooldown") emdash.SpaceTraders.models.shared.Cooldown cooldown, @JsonProperty("systems") emdash.SpaceTraders.models.shared.ScannedSystem[] systems) {
        this.cooldown = cooldown;
        this.systems = systems;
  }
}
