/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class CreateSurveyResponse {
    
    public String contentType;

    public CreateSurveyResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public CreateSurveyResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public CreateSurveyResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Created
     */
    
    public CreateSurvey201ApplicationJSON createSurvey201ApplicationJSONObject;

    public CreateSurveyResponse withCreateSurvey201ApplicationJSONObject(CreateSurvey201ApplicationJSON createSurvey201ApplicationJSONObject) {
        this.createSurvey201ApplicationJSONObject = createSurvey201ApplicationJSONObject;
        return this;
    }
    
    public CreateSurveyResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
