/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreateShipShipScan201ApplicationJSON - Created
 */
public class CreateShipShipScan201ApplicationJSON {
    @JsonProperty("data")
    public CreateShipShipScan201ApplicationJSONData data;

    public CreateShipShipScan201ApplicationJSON withData(CreateShipShipScan201ApplicationJSONData data) {
        this.data = data;
        return this;
    }
    
    public CreateShipShipScan201ApplicationJSON(@JsonProperty("data") CreateShipShipScan201ApplicationJSONData data) {
        this.data = data;
  }
}
