/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreateShipWaypointScan201ApplicationJSON - Created
 */
public class CreateShipWaypointScan201ApplicationJSON {
    @JsonProperty("data")
    public CreateShipWaypointScan201ApplicationJSONData data;

    public CreateShipWaypointScan201ApplicationJSON withData(CreateShipWaypointScan201ApplicationJSONData data) {
        this.data = data;
        return this;
    }
    
    public CreateShipWaypointScan201ApplicationJSON(@JsonProperty("data") CreateShipWaypointScan201ApplicationJSONData data) {
        this.data = data;
  }
}
