/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreateChart201ApplicationJSON - Created
 */
public class CreateChart201ApplicationJSON {
    @JsonProperty("data")
    public CreateChart201ApplicationJSONData data;

    public CreateChart201ApplicationJSON withData(CreateChart201ApplicationJSONData data) {
        this.data = data;
        return this;
    }
    
    public CreateChart201ApplicationJSON(@JsonProperty("data") CreateChart201ApplicationJSONData data) {
        this.data = data;
  }
}
