/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class DeliverContract200ApplicationJSONData {
    @JsonProperty("cargo")
    public emdash.SpaceTraders.models.shared.ShipCargo cargo;

    public DeliverContract200ApplicationJSONData withCargo(emdash.SpaceTraders.models.shared.ShipCargo cargo) {
        this.cargo = cargo;
        return this;
    }
    
    @JsonProperty("contract")
    public emdash.SpaceTraders.models.shared.Contract contract;

    public DeliverContract200ApplicationJSONData withContract(emdash.SpaceTraders.models.shared.Contract contract) {
        this.contract = contract;
        return this;
    }
    
    public DeliverContract200ApplicationJSONData(@JsonProperty("cargo") emdash.SpaceTraders.models.shared.ShipCargo cargo, @JsonProperty("contract") emdash.SpaceTraders.models.shared.Contract contract) {
        this.cargo = cargo;
        this.contract = contract;
  }
}
