/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class DeliverContractRequestBody {
    @JsonProperty("shipSymbol")
    public String shipSymbol;

    public DeliverContractRequestBody withShipSymbol(String shipSymbol) {
        this.shipSymbol = shipSymbol;
        return this;
    }
    
    @JsonProperty("tradeSymbol")
    public String tradeSymbol;

    public DeliverContractRequestBody withTradeSymbol(String tradeSymbol) {
        this.tradeSymbol = tradeSymbol;
        return this;
    }
    
    @JsonProperty("units")
    public Long units;

    public DeliverContractRequestBody withUnits(Long units) {
        this.units = units;
        return this;
    }
    
    public DeliverContractRequestBody(@JsonProperty("shipSymbol") String shipSymbol, @JsonProperty("tradeSymbol") String tradeSymbol, @JsonProperty("units") Long units) {
        this.shipSymbol = shipSymbol;
        this.tradeSymbol = tradeSymbol;
        this.units = units;
  }
}
