/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * DeliverContract200ApplicationJSON - OK
 */
public class DeliverContract200ApplicationJSON {
    @JsonProperty("data")
    public DeliverContract200ApplicationJSONData data;

    public DeliverContract200ApplicationJSON withData(DeliverContract200ApplicationJSONData data) {
        this.data = data;
        return this;
    }
    
    public DeliverContract200ApplicationJSON(@JsonProperty("data") DeliverContract200ApplicationJSONData data) {
        this.data = data;
  }
}
