/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import emdash.SpaceTraders.utils.SpeakeasyMetadata;

public class DeliverContractRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public DeliverContractRequestBody requestBody;

    public DeliverContractRequest withRequestBody(DeliverContractRequestBody requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * The ID of the contract
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=contractId")
    public String contractId;

    public DeliverContractRequest withContractId(String contractId) {
        this.contractId = contractId;
        return this;
    }
    
    public DeliverContractRequest(@JsonProperty("contractId") String contractId) {
        this.contractId = contractId;
  }
}
