/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class DockShipResponse {
    
    public String contentType;

    public DockShipResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * The ship has successfully docked at it's current location.
     */
    
    public DockShipDockShip200Response dockShip200Response;

    public DockShipResponse withDockShip200Response(DockShipDockShip200Response dockShip200Response) {
        this.dockShip200Response = dockShip200Response;
        return this;
    }
    
    
    public Integer statusCode;

    public DockShipResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public DockShipResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public DockShipResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
