/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class DockShipDockShip200ResponseData {
    /**
     * The navigation information of the ship.
     */
    @JsonProperty("nav")
    public emdash.SpaceTraders.models.shared.ShipNav nav;

    public DockShipDockShip200ResponseData withNav(emdash.SpaceTraders.models.shared.ShipNav nav) {
        this.nav = nav;
        return this;
    }
    
    public DockShipDockShip200ResponseData(@JsonProperty("nav") emdash.SpaceTraders.models.shared.ShipNav nav) {
        this.nav = nav;
  }
}
