/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * DockShipDockShip200Response - The ship has successfully docked at it's current location.
 */
public class DockShipDockShip200Response {
    @JsonProperty("data")
    public DockShipDockShip200ResponseData data;

    public DockShipDockShip200Response withData(DockShipDockShip200ResponseData data) {
        this.data = data;
        return this;
    }
    
    public DockShipDockShip200Response(@JsonProperty("data") DockShipDockShip200ResponseData data) {
        this.data = data;
  }
}
