/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ExtractResourcesRequestBody {
    /**
     * A resource survey of a waypoint, detailing a specific extraction location and the types of resources that can be found there.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("survey")
    public emdash.SpaceTraders.models.shared.Survey survey;

    public ExtractResourcesRequestBody withSurvey(emdash.SpaceTraders.models.shared.Survey survey) {
        this.survey = survey;
        return this;
    }
    
    public ExtractResourcesRequestBody(){}
}
