/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import emdash.SpaceTraders.utils.SpeakeasyMetadata;

public class ExtractResourcesRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public ExtractResourcesRequestBody requestBody;

    public ExtractResourcesRequest withRequestBody(ExtractResourcesRequestBody requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * The ship symbol
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=shipSymbol")
    public String shipSymbol;

    public ExtractResourcesRequest withShipSymbol(String shipSymbol) {
        this.shipSymbol = shipSymbol;
        return this;
    }
    
    public ExtractResourcesRequest(@JsonProperty("shipSymbol") String shipSymbol) {
        this.shipSymbol = shipSymbol;
  }
}
