/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ExtractResourcesResponse {
    
    public String contentType;

    public ExtractResourcesResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public ExtractResourcesResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ExtractResourcesResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Created
     */
    
    public ExtractResources201ApplicationJSON extractResources201ApplicationJSONObject;

    public ExtractResourcesResponse withExtractResources201ApplicationJSONObject(ExtractResources201ApplicationJSON extractResources201ApplicationJSONObject) {
        this.extractResources201ApplicationJSONObject = extractResources201ApplicationJSONObject;
        return this;
    }
    
    public ExtractResourcesResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
