/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class ExtractResources201ApplicationJSONData {
    @JsonProperty("cargo")
    public emdash.SpaceTraders.models.shared.ShipCargo cargo;

    public ExtractResources201ApplicationJSONData withCargo(emdash.SpaceTraders.models.shared.ShipCargo cargo) {
        this.cargo = cargo;
        return this;
    }
    
    /**
     * A cooldown is a period of time in which a ship cannot perform certain actions.
     */
    @JsonProperty("cooldown")
    public emdash.SpaceTraders.models.shared.Cooldown cooldown;

    public ExtractResources201ApplicationJSONData withCooldown(emdash.SpaceTraders.models.shared.Cooldown cooldown) {
        this.cooldown = cooldown;
        return this;
    }
    
    @JsonProperty("extraction")
    public emdash.SpaceTraders.models.shared.Extraction extraction;

    public ExtractResources201ApplicationJSONData withExtraction(emdash.SpaceTraders.models.shared.Extraction extraction) {
        this.extraction = extraction;
        return this;
    }
    
    public ExtractResources201ApplicationJSONData(@JsonProperty("cargo") emdash.SpaceTraders.models.shared.ShipCargo cargo, @JsonProperty("cooldown") emdash.SpaceTraders.models.shared.Cooldown cooldown, @JsonProperty("extraction") emdash.SpaceTraders.models.shared.Extraction extraction) {
        this.cargo = cargo;
        this.cooldown = cooldown;
        this.extraction = extraction;
  }
}
