/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ExtractResources201ApplicationJSON - Created
 */
public class ExtractResources201ApplicationJSON {
    @JsonProperty("data")
    public ExtractResources201ApplicationJSONData data;

    public ExtractResources201ApplicationJSON withData(ExtractResources201ApplicationJSONData data) {
        this.data = data;
        return this;
    }
    
    public ExtractResources201ApplicationJSON(@JsonProperty("data") ExtractResources201ApplicationJSONData data) {
        this.data = data;
  }
}
