/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class FulfillContract200ApplicationJSONData {
    @JsonProperty("agent")
    public emdash.SpaceTraders.models.shared.Agent agent;

    public FulfillContract200ApplicationJSONData withAgent(emdash.SpaceTraders.models.shared.Agent agent) {
        this.agent = agent;
        return this;
    }
    
    @JsonProperty("contract")
    public emdash.SpaceTraders.models.shared.Contract contract;

    public FulfillContract200ApplicationJSONData withContract(emdash.SpaceTraders.models.shared.Contract contract) {
        this.contract = contract;
        return this;
    }
    
    public FulfillContract200ApplicationJSONData(@JsonProperty("agent") emdash.SpaceTraders.models.shared.Agent agent, @JsonProperty("contract") emdash.SpaceTraders.models.shared.Contract contract) {
        this.agent = agent;
        this.contract = contract;
  }
}
