/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * FulfillContract200ApplicationJSON - OK
 */
public class FulfillContract200ApplicationJSON {
    @JsonProperty("data")
    public FulfillContract200ApplicationJSONData data;

    public FulfillContract200ApplicationJSON withData(FulfillContract200ApplicationJSONData data) {
        this.data = data;
        return this;
    }
    
    public FulfillContract200ApplicationJSON(@JsonProperty("data") FulfillContract200ApplicationJSONData data) {
        this.data = data;
  }
}
