/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetContract200ApplicationJSON - OK
 */
public class GetContract200ApplicationJSON {
    @JsonProperty("data")
    public emdash.SpaceTraders.models.shared.Contract data;

    public GetContract200ApplicationJSON withData(emdash.SpaceTraders.models.shared.Contract data) {
        this.data = data;
        return this;
    }
    
    public GetContract200ApplicationJSON(@JsonProperty("data") emdash.SpaceTraders.models.shared.Contract data) {
        this.data = data;
  }
}
