/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetContracts200ApplicationJSON - OK
 */
public class GetContracts200ApplicationJSON {
    @JsonProperty("data")
    public emdash.SpaceTraders.models.shared.Contract[] data;

    public GetContracts200ApplicationJSON withData(emdash.SpaceTraders.models.shared.Contract[] data) {
        this.data = data;
        return this;
    }
    
    @JsonProperty("meta")
    public emdash.SpaceTraders.models.shared.Meta meta;

    public GetContracts200ApplicationJSON withMeta(emdash.SpaceTraders.models.shared.Meta meta) {
        this.meta = meta;
        return this;
    }
    
    public GetContracts200ApplicationJSON(@JsonProperty("data") emdash.SpaceTraders.models.shared.Contract[] data, @JsonProperty("meta") emdash.SpaceTraders.models.shared.Meta meta) {
        this.data = data;
        this.meta = meta;
  }
}
