/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetContractsResponse {
    
    public String contentType;

    public GetContractsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetContractsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetContractsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public GetContracts200ApplicationJSON getContracts200ApplicationJSONObject;

    public GetContractsResponse withGetContracts200ApplicationJSONObject(GetContracts200ApplicationJSON getContracts200ApplicationJSONObject) {
        this.getContracts200ApplicationJSONObject = getContracts200ApplicationJSONObject;
        return this;
    }
    
    public GetContractsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
