/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetFactionsResponse {
    
    public String contentType;

    public GetFactionsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetFactionsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetFactionsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    
    public GetFactions200ApplicationJSON getFactions200ApplicationJSONObject;

    public GetFactionsResponse withGetFactions200ApplicationJSONObject(GetFactions200ApplicationJSON getFactions200ApplicationJSONObject) {
        this.getFactions200ApplicationJSONObject = getFactions200ApplicationJSONObject;
        return this;
    }
    
    public GetFactionsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
