/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetFaction200ApplicationJSON - OK
 */
public class GetFaction200ApplicationJSON {
    @JsonProperty("data")
    public emdash.SpaceTraders.models.shared.Faction data;

    public GetFaction200ApplicationJSON withData(emdash.SpaceTraders.models.shared.Faction data) {
        this.data = data;
        return this;
    }
    
    public GetFaction200ApplicationJSON(@JsonProperty("data") emdash.SpaceTraders.models.shared.Faction data) {
        this.data = data;
  }
}
