/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import emdash.SpaceTraders.utils.SpeakeasyMetadata;

public class GetFactionRequest {
    /**
     * The faction symbol
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=factionSymbol")
    public String factionSymbol;

    public GetFactionRequest withFactionSymbol(String factionSymbol) {
        this.factionSymbol = factionSymbol;
        return this;
    }
    
    public GetFactionRequest(@JsonProperty("factionSymbol") String factionSymbol) {
        this.factionSymbol = factionSymbol;
  }
}
