/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class GetFactions200ApplicationJSON {
    @JsonProperty("data")
    public emdash.SpaceTraders.models.shared.Faction[] data;

    public GetFactions200ApplicationJSON withData(emdash.SpaceTraders.models.shared.Faction[] data) {
        this.data = data;
        return this;
    }
    
    @JsonProperty("meta")
    public emdash.SpaceTraders.models.shared.Meta meta;

    public GetFactions200ApplicationJSON withMeta(emdash.SpaceTraders.models.shared.Meta meta) {
        this.meta = meta;
        return this;
    }
    
    public GetFactions200ApplicationJSON(@JsonProperty("data") emdash.SpaceTraders.models.shared.Faction[] data, @JsonProperty("meta") emdash.SpaceTraders.models.shared.Meta meta) {
        this.data = data;
        this.meta = meta;
  }
}
