/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetJumpGate200ApplicationJSON - OK
 */
public class GetJumpGate200ApplicationJSON {
    @JsonProperty("data")
    public emdash.SpaceTraders.models.shared.JumpGate data;

    public GetJumpGate200ApplicationJSON withData(emdash.SpaceTraders.models.shared.JumpGate data) {
        this.data = data;
        return this;
    }
    
    public GetJumpGate200ApplicationJSON(@JsonProperty("data") emdash.SpaceTraders.models.shared.JumpGate data) {
        this.data = data;
  }
}
