/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetMarket200ApplicationJSON - OK
 */
public class GetMarket200ApplicationJSON {
    @JsonProperty("data")
    public emdash.SpaceTraders.models.shared.Market data;

    public GetMarket200ApplicationJSON withData(emdash.SpaceTraders.models.shared.Market data) {
        this.data = data;
        return this;
    }
    
    public GetMarket200ApplicationJSON(@JsonProperty("data") emdash.SpaceTraders.models.shared.Market data) {
        this.data = data;
  }
}
