/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetMarketResponse {
    
    public String contentType;

    public GetMarketResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetMarketResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetMarketResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public GetMarket200ApplicationJSON getMarket200ApplicationJSONObject;

    public GetMarketResponse withGetMarket200ApplicationJSONObject(GetMarket200ApplicationJSON getMarket200ApplicationJSONObject) {
        this.getMarket200ApplicationJSONObject = getMarket200ApplicationJSONObject;
        return this;
    }
    
    public GetMarketResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
