/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetMyShipCargo200ApplicationJSON - OK
 */
public class GetMyShipCargo200ApplicationJSON {
    @JsonProperty("data")
    public emdash.SpaceTraders.models.shared.ShipCargo data;

    public GetMyShipCargo200ApplicationJSON withData(emdash.SpaceTraders.models.shared.ShipCargo data) {
        this.data = data;
        return this;
    }
    
    public GetMyShipCargo200ApplicationJSON(@JsonProperty("data") emdash.SpaceTraders.models.shared.ShipCargo data) {
        this.data = data;
  }
}
