/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetMyAgentResponse {
    
    public String contentType;

    public GetMyAgentResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetMyAgentResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetMyAgentResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public GetMyAgent200ApplicationJSON getMyAgent200ApplicationJSONObject;

    public GetMyAgentResponse withGetMyAgent200ApplicationJSONObject(GetMyAgent200ApplicationJSON getMyAgent200ApplicationJSONObject) {
        this.getMyAgent200ApplicationJSONObject = getMyAgent200ApplicationJSONObject;
        return this;
    }
    
    public GetMyAgentResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
