/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import emdash.SpaceTraders.utils.SpeakeasyMetadata;

public class GetMyShipCargoRequest {
    /**
     * The symbol of the ship
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=shipSymbol")
    public String shipSymbol;

    public GetMyShipCargoRequest withShipSymbol(String shipSymbol) {
        this.shipSymbol = shipSymbol;
        return this;
    }
    
    public GetMyShipCargoRequest(@JsonProperty("shipSymbol") String shipSymbol) {
        this.shipSymbol = shipSymbol;
  }
}
