/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetMyShip200ApplicationJSON - OK
 */
public class GetMyShip200ApplicationJSON {
    /**
     * A ship
     */
    @JsonProperty("data")
    public emdash.SpaceTraders.models.shared.Ship data;

    public GetMyShip200ApplicationJSON withData(emdash.SpaceTraders.models.shared.Ship data) {
        this.data = data;
        return this;
    }
    
    public GetMyShip200ApplicationJSON(@JsonProperty("data") emdash.SpaceTraders.models.shared.Ship data) {
        this.data = data;
  }
}
