/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetMyShipResponse {
    
    public String contentType;

    public GetMyShipResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetMyShipResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetMyShipResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public GetMyShip200ApplicationJSON getMyShip200ApplicationJSONObject;

    public GetMyShipResponse withGetMyShip200ApplicationJSONObject(GetMyShip200ApplicationJSON getMyShip200ApplicationJSONObject) {
        this.getMyShip200ApplicationJSONObject = getMyShip200ApplicationJSONObject;
        return this;
    }
    
    public GetMyShipResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
