/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetMyShipsResponse {
    
    public String contentType;

    public GetMyShipsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetMyShipsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetMyShipsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public GetMyShips200ApplicationJSON getMyShips200ApplicationJSONObject;

    public GetMyShipsResponse withGetMyShips200ApplicationJSONObject(GetMyShips200ApplicationJSON getMyShips200ApplicationJSONObject) {
        this.getMyShips200ApplicationJSONObject = getMyShips200ApplicationJSONObject;
        return this;
    }
    
    public GetMyShipsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
