/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetMyAgent200ApplicationJSON - OK
 */
public class GetMyAgent200ApplicationJSON {
    @JsonProperty("data")
    public emdash.SpaceTraders.models.shared.Agent data;

    public GetMyAgent200ApplicationJSON withData(emdash.SpaceTraders.models.shared.Agent data) {
        this.data = data;
        return this;
    }
    
    public GetMyAgent200ApplicationJSON(@JsonProperty("data") emdash.SpaceTraders.models.shared.Agent data) {
        this.data = data;
  }
}
