/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import emdash.SpaceTraders.utils.SpeakeasyMetadata;

public class GetSystemsRequest {
    /**
     * How many entries to return per page
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")
    public Long limit;

    public GetSystemsRequest withLimit(Long limit) {
        this.limit = limit;
        return this;
    }
    
    /**
     * What entry offset to request
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page")
    public Long page;

    public GetSystemsRequest withPage(Long page) {
        this.page = page;
        return this;
    }
    
    public GetSystemsRequest(){}
}
