/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetShipyardResponse {
    
    public String contentType;

    public GetShipyardResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetShipyardResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetShipyardResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public GetShipyard200ApplicationJSON getShipyard200ApplicationJSONObject;

    public GetShipyardResponse withGetShipyard200ApplicationJSONObject(GetShipyard200ApplicationJSON getShipyard200ApplicationJSONObject) {
        this.getShipyard200ApplicationJSONObject = getShipyard200ApplicationJSONObject;
        return this;
    }
    
    public GetShipyardResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
