/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class GetStatus200ApplicationJSONServerResets {
    /**
     * How often we intend to reset the game server.
     */
    @JsonProperty("frequency")
    public String frequency;

    public GetStatus200ApplicationJSONServerResets withFrequency(String frequency) {
        this.frequency = frequency;
        return this;
    }
    
    /**
     * The date and time when the game server will reset.
     */
    @JsonProperty("next")
    public String next;

    public GetStatus200ApplicationJSONServerResets withNext(String next) {
        this.next = next;
        return this;
    }
    
    public GetStatus200ApplicationJSONServerResets(@JsonProperty("frequency") String frequency, @JsonProperty("next") String next) {
        this.frequency = frequency;
        this.next = next;
  }
}
