/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetSystemsResponse {
    
    public String contentType;

    public GetSystemsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetSystemsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetSystemsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public GetSystems200ApplicationJSON getSystems200ApplicationJSONObject;

    public GetSystemsResponse withGetSystems200ApplicationJSONObject(GetSystems200ApplicationJSON getSystems200ApplicationJSONObject) {
        this.getSystems200ApplicationJSONObject = getSystems200ApplicationJSONObject;
        return this;
    }
    
    public GetSystemsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
