/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetSystem200ApplicationJSON - OK
 */
public class GetSystem200ApplicationJSON {
    @JsonProperty("data")
    public emdash.SpaceTraders.models.shared.System data;

    public GetSystem200ApplicationJSON withData(emdash.SpaceTraders.models.shared.System data) {
        this.data = data;
        return this;
    }
    
    public GetSystem200ApplicationJSON(@JsonProperty("data") emdash.SpaceTraders.models.shared.System data) {
        this.data = data;
  }
}
