/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import emdash.SpaceTraders.utils.SpeakeasyMetadata;

public class GetSystemWaypointsRequest {
    /**
     * How many entries to return per page
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")
    public Long limit;

    public GetSystemWaypointsRequest withLimit(Long limit) {
        this.limit = limit;
        return this;
    }
    
    /**
     * What entry offset to request
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page")
    public Long page;

    public GetSystemWaypointsRequest withPage(Long page) {
        this.page = page;
        return this;
    }
    
    /**
     * The system symbol
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=systemSymbol")
    public String systemSymbol;

    public GetSystemWaypointsRequest withSystemSymbol(String systemSymbol) {
        this.systemSymbol = systemSymbol;
        return this;
    }
    
    public GetSystemWaypointsRequest(@JsonProperty("systemSymbol") String systemSymbol) {
        this.systemSymbol = systemSymbol;
  }
}
