/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class GetStatus200ApplicationJSONLeaderboardsMostSubmittedCharts {
    @JsonProperty("agentSymbol")
    public String agentSymbol;

    public GetStatus200ApplicationJSONLeaderboardsMostSubmittedCharts withAgentSymbol(String agentSymbol) {
        this.agentSymbol = agentSymbol;
        return this;
    }
    
    @JsonProperty("chartCount")
    public Long chartCount;

    public GetStatus200ApplicationJSONLeaderboardsMostSubmittedCharts withChartCount(Long chartCount) {
        this.chartCount = chartCount;
        return this;
    }
    
    public GetStatus200ApplicationJSONLeaderboardsMostSubmittedCharts(@JsonProperty("agentSymbol") String agentSymbol, @JsonProperty("chartCount") Long chartCount) {
        this.agentSymbol = agentSymbol;
        this.chartCount = chartCount;
  }
}
