/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class GetStatus200ApplicationJSONLeaderboards {
    @JsonProperty("mostCredits")
    public GetStatus200ApplicationJSONLeaderboardsMostCredits[] mostCredits;

    public GetStatus200ApplicationJSONLeaderboards withMostCredits(GetStatus200ApplicationJSONLeaderboardsMostCredits[] mostCredits) {
        this.mostCredits = mostCredits;
        return this;
    }
    
    @JsonProperty("mostSubmittedCharts")
    public GetStatus200ApplicationJSONLeaderboardsMostSubmittedCharts[] mostSubmittedCharts;

    public GetStatus200ApplicationJSONLeaderboards withMostSubmittedCharts(GetStatus200ApplicationJSONLeaderboardsMostSubmittedCharts[] mostSubmittedCharts) {
        this.mostSubmittedCharts = mostSubmittedCharts;
        return this;
    }
    
    public GetStatus200ApplicationJSONLeaderboards(@JsonProperty("mostCredits") GetStatus200ApplicationJSONLeaderboardsMostCredits[] mostCredits, @JsonProperty("mostSubmittedCharts") GetStatus200ApplicationJSONLeaderboardsMostSubmittedCharts[] mostSubmittedCharts) {
        this.mostCredits = mostCredits;
        this.mostSubmittedCharts = mostSubmittedCharts;
  }
}
