/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetStatus200ApplicationJSON - OK
 */
public class GetStatus200ApplicationJSON {
    @JsonProperty("announcements")
    public GetStatus200ApplicationJSONAnnouncements[] announcements;

    public GetStatus200ApplicationJSON withAnnouncements(GetStatus200ApplicationJSONAnnouncements[] announcements) {
        this.announcements = announcements;
        return this;
    }
    
    @JsonProperty("description")
    public String description;

    public GetStatus200ApplicationJSON withDescription(String description) {
        this.description = description;
        return this;
    }
    
    @JsonProperty("leaderboards")
    public GetStatus200ApplicationJSONLeaderboards leaderboards;

    public GetStatus200ApplicationJSON withLeaderboards(GetStatus200ApplicationJSONLeaderboards leaderboards) {
        this.leaderboards = leaderboards;
        return this;
    }
    
    @JsonProperty("links")
    public GetStatus200ApplicationJSONLinks[] links;

    public GetStatus200ApplicationJSON withLinks(GetStatus200ApplicationJSONLinks[] links) {
        this.links = links;
        return this;
    }
    
    /**
     * The date and time when the game server was last reset.
     */
    @JsonProperty("resetDate")
    public String resetDate;

    public GetStatus200ApplicationJSON withResetDate(String resetDate) {
        this.resetDate = resetDate;
        return this;
    }
    
    @JsonProperty("serverResets")
    public GetStatus200ApplicationJSONServerResets serverResets;

    public GetStatus200ApplicationJSON withServerResets(GetStatus200ApplicationJSONServerResets serverResets) {
        this.serverResets = serverResets;
        return this;
    }
    
    @JsonProperty("stats")
    public GetStatus200ApplicationJSONStats stats;

    public GetStatus200ApplicationJSON withStats(GetStatus200ApplicationJSONStats stats) {
        this.stats = stats;
        return this;
    }
    
    /**
     * The current status of the game server.
     */
    @JsonProperty("status")
    public String status;

    public GetStatus200ApplicationJSON withStatus(String status) {
        this.status = status;
        return this;
    }
    
    /**
     * The current version of the API.
     */
    @JsonProperty("version")
    public String version;

    public GetStatus200ApplicationJSON withVersion(String version) {
        this.version = version;
        return this;
    }
    
    public GetStatus200ApplicationJSON(@JsonProperty("announcements") GetStatus200ApplicationJSONAnnouncements[] announcements, @JsonProperty("description") String description, @JsonProperty("leaderboards") GetStatus200ApplicationJSONLeaderboards leaderboards, @JsonProperty("links") GetStatus200ApplicationJSONLinks[] links, @JsonProperty("resetDate") String resetDate, @JsonProperty("serverResets") GetStatus200ApplicationJSONServerResets serverResets, @JsonProperty("stats") GetStatus200ApplicationJSONStats stats, @JsonProperty("status") String status, @JsonProperty("version") String version) {
        this.announcements = announcements;
        this.description = description;
        this.leaderboards = leaderboards;
        this.links = links;
        this.resetDate = resetDate;
        this.serverResets = serverResets;
        this.stats = stats;
        this.status = status;
        this.version = version;
  }
}
