/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetShipNavResponse {
    
    public String contentType;

    public GetShipNavResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetShipNavResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetShipNavResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * The current nav status of the ship.
     */
    
    public GetShipNav200ApplicationJSON getShipNav200ApplicationJSONObject;

    public GetShipNavResponse withGetShipNav200ApplicationJSONObject(GetShipNav200ApplicationJSON getShipNav200ApplicationJSONObject) {
        this.getShipNav200ApplicationJSONObject = getShipNav200ApplicationJSONObject;
        return this;
    }
    
    public GetShipNavResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
