/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetShipyard200ApplicationJSON - OK
 */
public class GetShipyard200ApplicationJSON {
    @JsonProperty("data")
    public emdash.SpaceTraders.models.shared.Shipyard data;

    public GetShipyard200ApplicationJSON withData(emdash.SpaceTraders.models.shared.Shipyard data) {
        this.data = data;
        return this;
    }
    
    public GetShipyard200ApplicationJSON(@JsonProperty("data") emdash.SpaceTraders.models.shared.Shipyard data) {
        this.data = data;
  }
}
