/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import emdash.SpaceTraders.utils.SpeakeasyMetadata;

public class GetSystemRequest {
    /**
     * The system symbol
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=systemSymbol")
    public String systemSymbol;

    public GetSystemRequest withSystemSymbol(String systemSymbol) {
        this.systemSymbol = systemSymbol;
        return this;
    }
    
    public GetSystemRequest(@JsonProperty("systemSymbol") String systemSymbol) {
        this.systemSymbol = systemSymbol;
  }
}
