/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class GetStatus200ApplicationJSONStats {
    @JsonProperty("agents")
    public Long agents;

    public GetStatus200ApplicationJSONStats withAgents(Long agents) {
        this.agents = agents;
        return this;
    }
    
    @JsonProperty("ships")
    public Long ships;

    public GetStatus200ApplicationJSONStats withShips(Long ships) {
        this.ships = ships;
        return this;
    }
    
    @JsonProperty("systems")
    public Long systems;

    public GetStatus200ApplicationJSONStats withSystems(Long systems) {
        this.systems = systems;
        return this;
    }
    
    @JsonProperty("waypoints")
    public Long waypoints;

    public GetStatus200ApplicationJSONStats withWaypoints(Long waypoints) {
        this.waypoints = waypoints;
        return this;
    }
    
    public GetStatus200ApplicationJSONStats(@JsonProperty("agents") Long agents, @JsonProperty("ships") Long ships, @JsonProperty("systems") Long systems, @JsonProperty("waypoints") Long waypoints) {
        this.agents = agents;
        this.ships = ships;
        this.systems = systems;
        this.waypoints = waypoints;
  }
}
