/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetSystemWaypoints200ApplicationJSON - OK
 */
public class GetSystemWaypoints200ApplicationJSON {
    @JsonProperty("data")
    public emdash.SpaceTraders.models.shared.Waypoint[] data;

    public GetSystemWaypoints200ApplicationJSON withData(emdash.SpaceTraders.models.shared.Waypoint[] data) {
        this.data = data;
        return this;
    }
    
    @JsonProperty("meta")
    public emdash.SpaceTraders.models.shared.Meta meta;

    public GetSystemWaypoints200ApplicationJSON withMeta(emdash.SpaceTraders.models.shared.Meta meta) {
        this.meta = meta;
        return this;
    }
    
    public GetSystemWaypoints200ApplicationJSON(@JsonProperty("data") emdash.SpaceTraders.models.shared.Waypoint[] data, @JsonProperty("meta") emdash.SpaceTraders.models.shared.Meta meta) {
        this.data = data;
        this.meta = meta;
  }
}
