/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class GetStatus200ApplicationJSONLinks {
    @JsonProperty("name")
    public String name;

    public GetStatus200ApplicationJSONLinks withName(String name) {
        this.name = name;
        return this;
    }
    
    @JsonProperty("url")
    public String url;

    public GetStatus200ApplicationJSONLinks withUrl(String url) {
        this.url = url;
        return this;
    }
    
    public GetStatus200ApplicationJSONLinks(@JsonProperty("name") String name, @JsonProperty("url") String url) {
        this.name = name;
        this.url = url;
  }
}
