/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetShipNav200ApplicationJSON - The current nav status of the ship.
 */
public class GetShipNav200ApplicationJSON {
    /**
     * The navigation information of the ship.
     */
    @JsonProperty("data")
    public emdash.SpaceTraders.models.shared.ShipNav data;

    public GetShipNav200ApplicationJSON withData(emdash.SpaceTraders.models.shared.ShipNav data) {
        this.data = data;
        return this;
    }
    
    public GetShipNav200ApplicationJSON(@JsonProperty("data") emdash.SpaceTraders.models.shared.ShipNav data) {
        this.data = data;
  }
}
