/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class GetStatus200ApplicationJSONAnnouncements {
    @JsonProperty("body")
    public String body;

    public GetStatus200ApplicationJSONAnnouncements withBody(String body) {
        this.body = body;
        return this;
    }
    
    @JsonProperty("title")
    public String title;

    public GetStatus200ApplicationJSONAnnouncements withTitle(String title) {
        this.title = title;
        return this;
    }
    
    public GetStatus200ApplicationJSONAnnouncements(@JsonProperty("body") String body, @JsonProperty("title") String title) {
        this.body = body;
        this.title = title;
  }
}
