/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class GetStatus200ApplicationJSONLeaderboardsMostCredits {
    @JsonProperty("agentSymbol")
    public String agentSymbol;

    public GetStatus200ApplicationJSONLeaderboardsMostCredits withAgentSymbol(String agentSymbol) {
        this.agentSymbol = agentSymbol;
        return this;
    }
    
    @JsonProperty("credits")
    public Long credits;

    public GetStatus200ApplicationJSONLeaderboardsMostCredits withCredits(Long credits) {
        this.credits = credits;
        return this;
    }
    
    public GetStatus200ApplicationJSONLeaderboardsMostCredits(@JsonProperty("agentSymbol") String agentSymbol, @JsonProperty("credits") Long credits) {
        this.agentSymbol = agentSymbol;
        this.credits = credits;
  }
}
