/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetWaypointResponse {
    
    public String contentType;

    public GetWaypointResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetWaypointResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetWaypointResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public GetWaypoint200ApplicationJSON getWaypoint200ApplicationJSONObject;

    public GetWaypointResponse withGetWaypoint200ApplicationJSONObject(GetWaypoint200ApplicationJSON getWaypoint200ApplicationJSONObject) {
        this.getWaypoint200ApplicationJSONObject = getWaypoint200ApplicationJSONObject;
        return this;
    }
    
    public GetWaypointResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
