/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetWaypoint200ApplicationJSON - OK
 */
public class GetWaypoint200ApplicationJSON {
    /**
     * A waypoint is a location that ships can travel to such as a Planet, Moon or Space Station.
     */
    @JsonProperty("data")
    public emdash.SpaceTraders.models.shared.Waypoint data;

    public GetWaypoint200ApplicationJSON withData(emdash.SpaceTraders.models.shared.Waypoint data) {
        this.data = data;
        return this;
    }
    
    public GetWaypoint200ApplicationJSON(@JsonProperty("data") emdash.SpaceTraders.models.shared.Waypoint data) {
        this.data = data;
  }
}
