/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import emdash.SpaceTraders.utils.SpeakeasyMetadata;

public class GetWaypointRequest {
    /**
     * The system symbol
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=systemSymbol")
    public String systemSymbol;

    public GetWaypointRequest withSystemSymbol(String systemSymbol) {
        this.systemSymbol = systemSymbol;
        return this;
    }
    
    /**
     * The waypoint symbol
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=waypointSymbol")
    public String waypointSymbol;

    public GetWaypointRequest withWaypointSymbol(String waypointSymbol) {
        this.waypointSymbol = waypointSymbol;
        return this;
    }
    
    public GetWaypointRequest(@JsonProperty("systemSymbol") String systemSymbol, @JsonProperty("waypointSymbol") String waypointSymbol) {
        this.systemSymbol = systemSymbol;
        this.waypointSymbol = waypointSymbol;
  }
}
