/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Jettison200ApplicationJSON - OK
 */
public class Jettison200ApplicationJSON {
    @JsonProperty("data")
    public Jettison200ApplicationJSONData data;

    public Jettison200ApplicationJSON withData(Jettison200ApplicationJSONData data) {
        this.data = data;
        return this;
    }
    
    public Jettison200ApplicationJSON(@JsonProperty("data") Jettison200ApplicationJSONData data) {
        this.data = data;
  }
}
