/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class JumpShip200ApplicationJSONData {
    /**
     * A cooldown is a period of time in which a ship cannot perform certain actions.
     */
    @JsonProperty("cooldown")
    public emdash.SpaceTraders.models.shared.Cooldown cooldown;

    public JumpShip200ApplicationJSONData withCooldown(emdash.SpaceTraders.models.shared.Cooldown cooldown) {
        this.cooldown = cooldown;
        return this;
    }
    
    /**
     * The navigation information of the ship.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("nav")
    public emdash.SpaceTraders.models.shared.ShipNav nav;

    public JumpShip200ApplicationJSONData withNav(emdash.SpaceTraders.models.shared.ShipNav nav) {
        this.nav = nav;
        return this;
    }
    
    public JumpShip200ApplicationJSONData(@JsonProperty("cooldown") emdash.SpaceTraders.models.shared.Cooldown cooldown) {
        this.cooldown = cooldown;
  }
}
