/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * JumpShip200ApplicationJSON - OK
 */
public class JumpShip200ApplicationJSON {
    @JsonProperty("data")
    public JumpShip200ApplicationJSONData data;

    public JumpShip200ApplicationJSON withData(JumpShip200ApplicationJSONData data) {
        this.data = data;
        return this;
    }
    
    public JumpShip200ApplicationJSON(@JsonProperty("data") JumpShip200ApplicationJSONData data) {
        this.data = data;
  }
}
