/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class JumpShipRequestBody {
    /**
     * The system symbol to jump to.
     */
    @JsonProperty("systemSymbol")
    public String systemSymbol;

    public JumpShipRequestBody withSystemSymbol(String systemSymbol) {
        this.systemSymbol = systemSymbol;
        return this;
    }
    
    public JumpShipRequestBody(@JsonProperty("systemSymbol") String systemSymbol) {
        this.systemSymbol = systemSymbol;
  }
}
