/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class JumpShipResponse {
    
    public String contentType;

    public JumpShipResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public JumpShipResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public JumpShipResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public JumpShip200ApplicationJSON jumpShip200ApplicationJSONObject;

    public JumpShipResponse withJumpShip200ApplicationJSONObject(JumpShip200ApplicationJSON jumpShip200ApplicationJSONObject) {
        this.jumpShip200ApplicationJSONObject = jumpShip200ApplicationJSONObject;
        return this;
    }
    
    public JumpShipResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
