/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class NavigateShipRequestBody {
    /**
     * The target destination.
     */
    @JsonProperty("waypointSymbol")
    public String waypointSymbol;

    public NavigateShipRequestBody withWaypointSymbol(String waypointSymbol) {
        this.waypointSymbol = waypointSymbol;
        return this;
    }
    
    public NavigateShipRequestBody(@JsonProperty("waypointSymbol") String waypointSymbol) {
        this.waypointSymbol = waypointSymbol;
  }
}
