/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * NavigateShip200ApplicationJSON - The successful transit information including the route details and changes to ship fuel, supplies, and crew wages paid. The route includes the expected time of arrival.
 */
public class NavigateShip200ApplicationJSON {
    @JsonProperty("data")
    public NavigateShip200ApplicationJSONData data;

    public NavigateShip200ApplicationJSON withData(NavigateShip200ApplicationJSONData data) {
        this.data = data;
        return this;
    }
    
    public NavigateShip200ApplicationJSON(@JsonProperty("data") NavigateShip200ApplicationJSONData data) {
        this.data = data;
  }
}
