/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class NavigateShipResponse {
    
    public String contentType;

    public NavigateShipResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public NavigateShipResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public NavigateShipResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * The successful transit information including the route details and changes to ship fuel, supplies, and crew wages paid. The route includes the expected time of arrival.
     */
    
    public NavigateShip200ApplicationJSON navigateShip200ApplicationJSONObject;

    public NavigateShipResponse withNavigateShip200ApplicationJSONObject(NavigateShip200ApplicationJSON navigateShip200ApplicationJSONObject) {
        this.navigateShip200ApplicationJSONObject = navigateShip200ApplicationJSONObject;
        return this;
    }
    
    public NavigateShipResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
