/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * NegotiateContractNegotiateContract200Response - Created
 */
public class NegotiateContractNegotiateContract200Response {
    @JsonProperty("data")
    public NegotiateContractNegotiateContract200ResponseData data;

    public NegotiateContractNegotiateContract200Response withData(NegotiateContractNegotiateContract200ResponseData data) {
        this.data = data;
        return this;
    }
    
    public NegotiateContractNegotiateContract200Response(@JsonProperty("data") NegotiateContractNegotiateContract200ResponseData data) {
        this.data = data;
  }
}
