/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class NegotiateContractNegotiateContract200ResponseData {
    @JsonProperty("contract")
    public emdash.SpaceTraders.models.shared.Contract contract;

    public NegotiateContractNegotiateContract200ResponseData withContract(emdash.SpaceTraders.models.shared.Contract contract) {
        this.contract = contract;
        return this;
    }
    
    public NegotiateContractNegotiateContract200ResponseData(@JsonProperty("contract") emdash.SpaceTraders.models.shared.Contract contract) {
        this.contract = contract;
  }
}
