/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class NegotiateContractResponse {
    
    public String contentType;

    public NegotiateContractResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Created
     */
    
    public NegotiateContractNegotiateContract200Response negotiateContract200Response;

    public NegotiateContractResponse withNegotiateContract200Response(NegotiateContractNegotiateContract200Response negotiateContract200Response) {
        this.negotiateContract200Response = negotiateContract200Response;
        return this;
    }
    
    
    public Integer statusCode;

    public NegotiateContractResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public NegotiateContractResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public NegotiateContractResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
