/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * OrbitShipOrbitShip200Response - The ship has successfully moved into orbit at it's current location.
 */
public class OrbitShipOrbitShip200Response {
    @JsonProperty("data")
    public OrbitShipOrbitShip200ResponseData data;

    public OrbitShipOrbitShip200Response withData(OrbitShipOrbitShip200ResponseData data) {
        this.data = data;
        return this;
    }
    
    public OrbitShipOrbitShip200Response(@JsonProperty("data") OrbitShipOrbitShip200ResponseData data) {
        this.data = data;
  }
}
