/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class OrbitShipResponse {
    
    public String contentType;

    public OrbitShipResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * The ship has successfully moved into orbit at it's current location.
     */
    
    public OrbitShipOrbitShip200Response orbitShip200Response;

    public OrbitShipResponse withOrbitShip200Response(OrbitShipOrbitShip200Response orbitShip200Response) {
        this.orbitShip200Response = orbitShip200Response;
        return this;
    }
    
    
    public Integer statusCode;

    public OrbitShipResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public OrbitShipResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public OrbitShipResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
