/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class PatchShipNavResponse {
    
    public String contentType;

    public PatchShipNavResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public PatchShipNavResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public PatchShipNavResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * The updated nav status of the ship.
     */
    
    public PatchShipNav200ApplicationJSON patchShipNav200ApplicationJSONObject;

    public PatchShipNavResponse withPatchShipNav200ApplicationJSONObject(PatchShipNav200ApplicationJSON patchShipNav200ApplicationJSONObject) {
        this.patchShipNav200ApplicationJSONObject = patchShipNav200ApplicationJSONObject;
        return this;
    }
    
    public PatchShipNavResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
