/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import emdash.SpaceTraders.utils.SpeakeasyMetadata;

public class PatchShipNavRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public PatchShipNavRequestBody requestBody;

    public PatchShipNavRequest withRequestBody(PatchShipNavRequestBody requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * The ship symbol
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=shipSymbol")
    public String shipSymbol;

    public PatchShipNavRequest withShipSymbol(String shipSymbol) {
        this.shipSymbol = shipSymbol;
        return this;
    }
    
    public PatchShipNavRequest(@JsonProperty("shipSymbol") String shipSymbol) {
        this.shipSymbol = shipSymbol;
  }
}
