/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class PurchaseShipRequestBody {
    @JsonProperty("shipType")
    public emdash.SpaceTraders.models.shared.ShipType shipType;

    public PurchaseShipRequestBody withShipType(emdash.SpaceTraders.models.shared.ShipType shipType) {
        this.shipType = shipType;
        return this;
    }
    
    /**
     * The symbol of the waypoint you want to purchase the ship at.
     */
    @JsonProperty("waypointSymbol")
    public String waypointSymbol;

    public PurchaseShipRequestBody withWaypointSymbol(String waypointSymbol) {
        this.waypointSymbol = waypointSymbol;
        return this;
    }
    
    public PurchaseShipRequestBody(@JsonProperty("shipType") emdash.SpaceTraders.models.shared.ShipType shipType, @JsonProperty("waypointSymbol") String waypointSymbol) {
        this.shipType = shipType;
        this.waypointSymbol = waypointSymbol;
  }
}
