/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PurchaseCargoPurchaseCargo201Response - Created
 */
public class PurchaseCargoPurchaseCargo201Response {
    @JsonProperty("data")
    public PurchaseCargoPurchaseCargo201ResponseData data;

    public PurchaseCargoPurchaseCargo201Response withData(PurchaseCargoPurchaseCargo201ResponseData data) {
        this.data = data;
        return this;
    }
    
    public PurchaseCargoPurchaseCargo201Response(@JsonProperty("data") PurchaseCargoPurchaseCargo201ResponseData data) {
        this.data = data;
  }
}
