/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class PurchaseCargoResponse {
    
    public String contentType;

    public PurchaseCargoResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Created
     */
    
    public PurchaseCargoPurchaseCargo201Response purchaseCargo201Response;

    public PurchaseCargoResponse withPurchaseCargo201Response(PurchaseCargoPurchaseCargo201Response purchaseCargo201Response) {
        this.purchaseCargo201Response = purchaseCargo201Response;
        return this;
    }
    
    
    public Integer statusCode;

    public PurchaseCargoResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public PurchaseCargoResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public PurchaseCargoResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
