/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class PurchaseShipResponse {
    
    public String contentType;

    public PurchaseShipResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public PurchaseShipResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public PurchaseShipResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Created
     */
    
    public PurchaseShip201ApplicationJSON purchaseShip201ApplicationJSONObject;

    public PurchaseShipResponse withPurchaseShip201ApplicationJSONObject(PurchaseShip201ApplicationJSON purchaseShip201ApplicationJSONObject) {
        this.purchaseShip201ApplicationJSONObject = purchaseShip201ApplicationJSONObject;
        return this;
    }
    
    public PurchaseShipResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
