/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class PurchaseCargoPurchaseCargoRequest {
    @JsonProperty("symbol")
    public String symbol;

    public PurchaseCargoPurchaseCargoRequest withSymbol(String symbol) {
        this.symbol = symbol;
        return this;
    }
    
    @JsonProperty("units")
    public Long units;

    public PurchaseCargoPurchaseCargoRequest withUnits(Long units) {
        this.units = units;
        return this;
    }
    
    public PurchaseCargoPurchaseCargoRequest(@JsonProperty("symbol") String symbol, @JsonProperty("units") Long units) {
        this.symbol = symbol;
        this.units = units;
  }
}
