/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class PurchaseCargoPurchaseCargo201ResponseData {
    @JsonProperty("agent")
    public emdash.SpaceTraders.models.shared.Agent agent;

    public PurchaseCargoPurchaseCargo201ResponseData withAgent(emdash.SpaceTraders.models.shared.Agent agent) {
        this.agent = agent;
        return this;
    }
    
    @JsonProperty("cargo")
    public emdash.SpaceTraders.models.shared.ShipCargo cargo;

    public PurchaseCargoPurchaseCargo201ResponseData withCargo(emdash.SpaceTraders.models.shared.ShipCargo cargo) {
        this.cargo = cargo;
        return this;
    }
    
    @JsonProperty("transaction")
    public emdash.SpaceTraders.models.shared.MarketTransaction transaction;

    public PurchaseCargoPurchaseCargo201ResponseData withTransaction(emdash.SpaceTraders.models.shared.MarketTransaction transaction) {
        this.transaction = transaction;
        return this;
    }
    
    public PurchaseCargoPurchaseCargo201ResponseData(@JsonProperty("agent") emdash.SpaceTraders.models.shared.Agent agent, @JsonProperty("cargo") emdash.SpaceTraders.models.shared.ShipCargo cargo, @JsonProperty("transaction") emdash.SpaceTraders.models.shared.MarketTransaction transaction) {
        this.agent = agent;
        this.cargo = cargo;
        this.transaction = transaction;
  }
}
