/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class RefuelShipResponse {
    
    public String contentType;

    public RefuelShipResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public RefuelShipResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public RefuelShipResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public RefuelShip200ApplicationJSON refuelShip200ApplicationJSONObject;

    public RefuelShipResponse withRefuelShip200ApplicationJSONObject(RefuelShip200ApplicationJSON refuelShip200ApplicationJSONObject) {
        this.refuelShip200ApplicationJSONObject = refuelShip200ApplicationJSONObject;
        return this;
    }
    
    public RefuelShipResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
