/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class RefuelShip200ApplicationJSONData {
    @JsonProperty("agent")
    public emdash.SpaceTraders.models.shared.Agent agent;

    public RefuelShip200ApplicationJSONData withAgent(emdash.SpaceTraders.models.shared.Agent agent) {
        this.agent = agent;
        return this;
    }
    
    /**
     * Details of the ship's fuel tanks including how much fuel was consumed during the last transit or action.
     */
    @JsonProperty("fuel")
    public emdash.SpaceTraders.models.shared.ShipFuel fuel;

    public RefuelShip200ApplicationJSONData withFuel(emdash.SpaceTraders.models.shared.ShipFuel fuel) {
        this.fuel = fuel;
        return this;
    }
    
    @JsonProperty("transaction")
    public emdash.SpaceTraders.models.shared.MarketTransaction transaction;

    public RefuelShip200ApplicationJSONData withTransaction(emdash.SpaceTraders.models.shared.MarketTransaction transaction) {
        this.transaction = transaction;
        return this;
    }
    
    public RefuelShip200ApplicationJSONData(@JsonProperty("agent") emdash.SpaceTraders.models.shared.Agent agent, @JsonProperty("fuel") emdash.SpaceTraders.models.shared.ShipFuel fuel, @JsonProperty("transaction") emdash.SpaceTraders.models.shared.MarketTransaction transaction) {
        this.agent = agent;
        this.fuel = fuel;
        this.transaction = transaction;
  }
}
