/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * RefuelShip200ApplicationJSON - OK
 */
public class RefuelShip200ApplicationJSON {
    @JsonProperty("data")
    public RefuelShip200ApplicationJSONData data;

    public RefuelShip200ApplicationJSON withData(RefuelShip200ApplicationJSONData data) {
        this.data = data;
        return this;
    }
    
    public RefuelShip200ApplicationJSON(@JsonProperty("data") RefuelShip200ApplicationJSONData data) {
        this.data = data;
  }
}
