/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class RegisterRequestBody {
    /**
     * Your email address. This is used if you reserved your call sign between resets.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("email")
    public String email;

    public RegisterRequestBody withEmail(String email) {
        this.email = email;
        return this;
    }
    
    /**
     * The faction you choose determines your headquarters.
     */
    @JsonProperty("faction")
    public RegisterRequestBodyFaction faction;

    public RegisterRequestBody withFaction(RegisterRequestBodyFaction faction) {
        this.faction = faction;
        return this;
    }
    
    /**
     * How other agents will see your ships and information.
     */
    @JsonProperty("symbol")
    public String symbol;

    public RegisterRequestBody withSymbol(String symbol) {
        this.symbol = symbol;
        return this;
    }
    
    public RegisterRequestBody(@JsonProperty("faction") RegisterRequestBodyFaction faction, @JsonProperty("symbol") String symbol) {
        this.faction = faction;
        this.symbol = symbol;
  }
}
