/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class Register201ApplicationJSONData {
    @JsonProperty("agent")
    public emdash.SpaceTraders.models.shared.Agent agent;

    public Register201ApplicationJSONData withAgent(emdash.SpaceTraders.models.shared.Agent agent) {
        this.agent = agent;
        return this;
    }
    
    @JsonProperty("contract")
    public emdash.SpaceTraders.models.shared.Contract contract;

    public Register201ApplicationJSONData withContract(emdash.SpaceTraders.models.shared.Contract contract) {
        this.contract = contract;
        return this;
    }
    
    @JsonProperty("faction")
    public emdash.SpaceTraders.models.shared.Faction faction;

    public Register201ApplicationJSONData withFaction(emdash.SpaceTraders.models.shared.Faction faction) {
        this.faction = faction;
        return this;
    }
    
    /**
     * A ship
     */
    @JsonProperty("ship")
    public emdash.SpaceTraders.models.shared.Ship ship;

    public Register201ApplicationJSONData withShip(emdash.SpaceTraders.models.shared.Ship ship) {
        this.ship = ship;
        return this;
    }
    
    /**
     * A Bearer token for accessing secured API endpoints.
     */
    @JsonProperty("token")
    public String token;

    public Register201ApplicationJSONData withToken(String token) {
        this.token = token;
        return this;
    }
    
    public Register201ApplicationJSONData(@JsonProperty("agent") emdash.SpaceTraders.models.shared.Agent agent, @JsonProperty("contract") emdash.SpaceTraders.models.shared.Contract contract, @JsonProperty("faction") emdash.SpaceTraders.models.shared.Faction faction, @JsonProperty("ship") emdash.SpaceTraders.models.shared.Ship ship, @JsonProperty("token") String token) {
        this.agent = agent;
        this.contract = contract;
        this.faction = faction;
        this.ship = ship;
        this.token = token;
  }
}
