/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Register201ApplicationJSON - OK
 */
public class Register201ApplicationJSON {
    @JsonProperty("data")
    public Register201ApplicationJSONData data;

    public Register201ApplicationJSON withData(Register201ApplicationJSONData data) {
        this.data = data;
        return this;
    }
    
    public Register201ApplicationJSON(@JsonProperty("data") Register201ApplicationJSONData data) {
        this.data = data;
  }
}
