/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * RegisterRequestBodyFaction - The faction you choose determines your headquarters.
 */
public enum RegisterRequestBodyFaction {
    COSMIC("COSMIC"),
    VOID_("VOID"),
    GALACTIC("GALACTIC"),
    QUANTUM("QUANTUM"),
    DOMINION("DOMINION");

    @JsonValue
    public final String value;

    private RegisterRequestBodyFaction(String value) {
        this.value = value;
    }
}
