/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * SellCargoSellCargo201Response - Created
 */
public class SellCargoSellCargo201Response {
    @JsonProperty("data")
    public SellCargoSellCargo201ResponseData data;

    public SellCargoSellCargo201Response withData(SellCargoSellCargo201ResponseData data) {
        this.data = data;
        return this;
    }
    
    public SellCargoSellCargo201Response(@JsonProperty("data") SellCargoSellCargo201ResponseData data) {
        this.data = data;
  }
}
