/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class ShipRefineRequestBody {
    @JsonProperty("produce")
    public ShipRefineRequestBodyProduce produce;

    public ShipRefineRequestBody withProduce(ShipRefineRequestBodyProduce produce) {
        this.produce = produce;
        return this;
    }
    
    public ShipRefineRequestBody(@JsonProperty("produce") ShipRefineRequestBodyProduce produce) {
        this.produce = produce;
  }
}
