/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ShipRefineShipRefine200ResponseDataConsumed {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tradeSymbol")
    public String tradeSymbol;

    public ShipRefineShipRefine200ResponseDataConsumed withTradeSymbol(String tradeSymbol) {
        this.tradeSymbol = tradeSymbol;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("units")
    public Long units;

    public ShipRefineShipRefine200ResponseDataConsumed withUnits(Long units) {
        this.units = units;
        return this;
    }
    
    public ShipRefineShipRefine200ResponseDataConsumed(){}
}
