/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ShipRefineShipRefine200Response - The ship has successfully started refining.
 */
public class ShipRefineShipRefine200Response {
    @JsonProperty("data")
    public ShipRefineShipRefine200ResponseData data;

    public ShipRefineShipRefine200Response withData(ShipRefineShipRefine200ResponseData data) {
        this.data = data;
        return this;
    }
    
    public ShipRefineShipRefine200Response(@JsonProperty("data") ShipRefineShipRefine200ResponseData data) {
        this.data = data;
  }
}
