/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import emdash.SpaceTraders.utils.SpeakeasyMetadata;

public class ShipRefineRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public ShipRefineRequestBody requestBody;

    public ShipRefineRequest withRequestBody(ShipRefineRequestBody requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * The symbol of the ship
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=shipSymbol")
    public String shipSymbol;

    public ShipRefineRequest withShipSymbol(String shipSymbol) {
        this.shipSymbol = shipSymbol;
        return this;
    }
    
    public ShipRefineRequest(@JsonProperty("shipSymbol") String shipSymbol) {
        this.shipSymbol = shipSymbol;
  }
}
