/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ShipRefineResponse {
    
    public String contentType;

    public ShipRefineResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * The ship has successfully started refining.
     */
    
    public ShipRefineShipRefine200Response shipRefine200Response;

    public ShipRefineResponse withShipRefine200Response(ShipRefineShipRefine200Response shipRefine200Response) {
        this.shipRefine200Response = shipRefine200Response;
        return this;
    }
    
    
    public Integer statusCode;

    public ShipRefineResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ShipRefineResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ShipRefineResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
