/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ShipRefineRequestBodyProduce {
    IRON("IRON"),
    COPPER("COPPER"),
    SILVER("SILVER"),
    GOLD("GOLD"),
    ALUMINUM("ALUMINUM"),
    PLATINUM("PLATINUM"),
    URANITE("URANITE"),
    MERITIUM("MERITIUM"),
    FUEL("FUEL");

    @JsonValue
    public final String value;

    private ShipRefineRequestBodyProduce(String value) {
        this.value = value;
    }
}
