/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class TransferCargoTransferCargo200ResponseData {
    @JsonProperty("cargo")
    public emdash.SpaceTraders.models.shared.ShipCargo cargo;

    public TransferCargoTransferCargo200ResponseData withCargo(emdash.SpaceTraders.models.shared.ShipCargo cargo) {
        this.cargo = cargo;
        return this;
    }
    
    public TransferCargoTransferCargo200ResponseData(@JsonProperty("cargo") emdash.SpaceTraders.models.shared.ShipCargo cargo) {
        this.cargo = cargo;
  }
}
