/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * TransferCargoTransferCargo200Response - Created
 */
public class TransferCargoTransferCargo200Response {
    @JsonProperty("data")
    public TransferCargoTransferCargo200ResponseData data;

    public TransferCargoTransferCargo200Response withData(TransferCargoTransferCargo200ResponseData data) {
        this.data = data;
        return this;
    }
    
    public TransferCargoTransferCargo200Response(@JsonProperty("data") TransferCargoTransferCargo200ResponseData data) {
        this.data = data;
  }
}
