/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class WarpShip200ApplicationJSONData {
    /**
     * Details of the ship's fuel tanks including how much fuel was consumed during the last transit or action.
     */
    @JsonProperty("fuel")
    public emdash.SpaceTraders.models.shared.ShipFuel fuel;

    public WarpShip200ApplicationJSONData withFuel(emdash.SpaceTraders.models.shared.ShipFuel fuel) {
        this.fuel = fuel;
        return this;
    }
    
    /**
     * The navigation information of the ship.
     */
    @JsonProperty("nav")
    public emdash.SpaceTraders.models.shared.ShipNav nav;

    public WarpShip200ApplicationJSONData withNav(emdash.SpaceTraders.models.shared.ShipNav nav) {
        this.nav = nav;
        return this;
    }
    
    public WarpShip200ApplicationJSONData(@JsonProperty("fuel") emdash.SpaceTraders.models.shared.ShipFuel fuel, @JsonProperty("nav") emdash.SpaceTraders.models.shared.ShipNav nav) {
        this.fuel = fuel;
        this.nav = nav;
  }
}
