/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * WarpShip200ApplicationJSON - The successful transit information including the route details and changes to ship fuel, supplies, and crew wages paid. The route includes the expected time of arrival.
 */
public class WarpShip200ApplicationJSON {
    @JsonProperty("data")
    public WarpShip200ApplicationJSONData data;

    public WarpShip200ApplicationJSON withData(WarpShip200ApplicationJSONData data) {
        this.data = data;
        return this;
    }
    
    public WarpShip200ApplicationJSON(@JsonProperty("data") WarpShip200ApplicationJSONData data) {
        this.data = data;
  }
}
