/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders;

import emdash.SpaceTraders.utils.HTTPClient;
import emdash.SpaceTraders.models.shared.Security;

class SDKConfiguration {
	public HTTPClient defaultClient;
	public HTTPClient securityClient;
	public Security security;
	public String serverUrl;
	public int serverIdx = 0;
	public String language = "java";
	public String openapiDocVersion = "2.0.0";
	public String sdkVersion = "1.3.1";
	public String genVersion = "2.37.2";
	
}