/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class Agent {
    @JsonProperty("accountId")
    public String accountId;

    public Agent withAccountId(String accountId) {
        this.accountId = accountId;
        return this;
    }
    
    /**
     * The number of credits the agent has available. Credits can be negative if funds have been overdrawn.
     */
    @JsonProperty("credits")
    public Long credits;

    public Agent withCredits(Long credits) {
        this.credits = credits;
        return this;
    }
    
    /**
     * The headquarters of the agent.
     */
    @JsonProperty("headquarters")
    public String headquarters;

    public Agent withHeadquarters(String headquarters) {
        this.headquarters = headquarters;
        return this;
    }
    
    /**
     * The faction the agent started with.
     */
    @JsonProperty("startingFaction")
    public String startingFaction;

    public Agent withStartingFaction(String startingFaction) {
        this.startingFaction = startingFaction;
        return this;
    }
    
    @JsonProperty("symbol")
    public String symbol;

    public Agent withSymbol(String symbol) {
        this.symbol = symbol;
        return this;
    }
    
    public Agent(@JsonProperty("accountId") String accountId, @JsonProperty("credits") Long credits, @JsonProperty("headquarters") String headquarters, @JsonProperty("startingFaction") String startingFaction, @JsonProperty("symbol") String symbol) {
        this.accountId = accountId;
        this.credits = credits;
        this.headquarters = headquarters;
        this.startingFaction = startingFaction;
        this.symbol = symbol;
  }
}
