/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ContractType {
    PROCUREMENT("PROCUREMENT"),
    TRANSPORT("TRANSPORT"),
    SHUTTLE("SHUTTLE");

    @JsonValue
    public final String value;

    private ContractType(String value) {
        this.value = value;
    }
}
