/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ContractDeliverGood - The details of a delivery contract. Includes the type of good, units needed, and the destination.
 */
public class ContractDeliverGood {
    /**
     * The destination where goods need to be delivered.
     */
    @JsonProperty("destinationSymbol")
    public String destinationSymbol;

    public ContractDeliverGood withDestinationSymbol(String destinationSymbol) {
        this.destinationSymbol = destinationSymbol;
        return this;
    }
    
    /**
     * The symbol of the trade good to deliver.
     */
    @JsonProperty("tradeSymbol")
    public String tradeSymbol;

    public ContractDeliverGood withTradeSymbol(String tradeSymbol) {
        this.tradeSymbol = tradeSymbol;
        return this;
    }
    
    /**
     * The number of units fulfilled on this contract.
     */
    @JsonProperty("unitsFulfilled")
    public Long unitsFulfilled;

    public ContractDeliverGood withUnitsFulfilled(Long unitsFulfilled) {
        this.unitsFulfilled = unitsFulfilled;
        return this;
    }
    
    /**
     * The number of units that need to be delivered on this contract.
     */
    @JsonProperty("unitsRequired")
    public Long unitsRequired;

    public ContractDeliverGood withUnitsRequired(Long unitsRequired) {
        this.unitsRequired = unitsRequired;
        return this;
    }
    
    public ContractDeliverGood(@JsonProperty("destinationSymbol") String destinationSymbol, @JsonProperty("tradeSymbol") String tradeSymbol, @JsonProperty("unitsFulfilled") Long unitsFulfilled, @JsonProperty("unitsRequired") Long unitsRequired) {
        this.destinationSymbol = destinationSymbol;
        this.tradeSymbol = tradeSymbol;
        this.unitsFulfilled = unitsFulfilled;
        this.unitsRequired = unitsRequired;
  }
}
