/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class Extraction {
    @JsonProperty("shipSymbol")
    public String shipSymbol;

    public Extraction withShipSymbol(String shipSymbol) {
        this.shipSymbol = shipSymbol;
        return this;
    }
    
    @JsonProperty("yield")
    public ExtractionYield yield;

    public Extraction withYield(ExtractionYield yield) {
        this.yield = yield;
        return this;
    }
    
    public Extraction(@JsonProperty("shipSymbol") String shipSymbol, @JsonProperty("yield") ExtractionYield yield) {
        this.shipSymbol = shipSymbol;
        this.yield = yield;
  }
}
