/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class ExtractionYield {
    @JsonProperty("symbol")
    public String symbol;

    public ExtractionYield withSymbol(String symbol) {
        this.symbol = symbol;
        return this;
    }
    
    /**
     * The number of units extracted that were placed into the ship's cargo hold.
     */
    @JsonProperty("units")
    public Long units;

    public ExtractionYield withUnits(Long units) {
        this.units = units;
        return this;
    }
    
    public ExtractionYield(@JsonProperty("symbol") String symbol, @JsonProperty("units") Long units) {
        this.symbol = symbol;
        this.units = units;
  }
}
