/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class JumpGate {
    /**
     * The systems within range of the gate that have a corresponding gate.
     */
    @JsonProperty("connectedSystems")
    public ConnectedSystem[] connectedSystems;

    public JumpGate withConnectedSystems(ConnectedSystem[] connectedSystems) {
        this.connectedSystems = connectedSystems;
        return this;
    }
    
    /**
     * The symbol of the faction that owns the gate.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("factionSymbol")
    public String factionSymbol;

    public JumpGate withFactionSymbol(String factionSymbol) {
        this.factionSymbol = factionSymbol;
        return this;
    }
    
    /**
     * The maximum jump range of the gate.
     */
    @JsonProperty("jumpRange")
    public Double jumpRange;

    public JumpGate withJumpRange(Double jumpRange) {
        this.jumpRange = jumpRange;
        return this;
    }
    
    public JumpGate(@JsonProperty("connectedSystems") ConnectedSystem[] connectedSystems, @JsonProperty("jumpRange") Double jumpRange) {
        this.connectedSystems = connectedSystems;
        this.jumpRange = jumpRange;
  }
}
