/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class Market {
    /**
     * The list of goods that are bought and sold between agents at this market.
     */
    @JsonProperty("exchange")
    public TradeGood[] exchange;

    public Market withExchange(TradeGood[] exchange) {
        this.exchange = exchange;
        return this;
    }
    
    /**
     * The list of goods that are exported from this market.
     */
    @JsonProperty("exports")
    public TradeGood[] exports;

    public Market withExports(TradeGood[] exports) {
        this.exports = exports;
        return this;
    }
    
    /**
     * The list of goods that are sought as imports in this market.
     */
    @JsonProperty("imports")
    public TradeGood[] imports;

    public Market withImports(TradeGood[] imports) {
        this.imports = imports;
        return this;
    }
    
    /**
     * The symbol of the market. The symbol is the same as the waypoint where the market is located.
     */
    @JsonProperty("symbol")
    public String symbol;

    public Market withSymbol(String symbol) {
        this.symbol = symbol;
        return this;
    }
    
    /**
     * The list of goods that are traded at this market. Visible only when a ship is present at the market.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tradeGoods")
    public MarketTradeGood[] tradeGoods;

    public Market withTradeGoods(MarketTradeGood[] tradeGoods) {
        this.tradeGoods = tradeGoods;
        return this;
    }
    
    /**
     * The list of recent transactions at this market. Visible only when a ship is present at the market.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("transactions")
    public MarketTransaction[] transactions;

    public Market withTransactions(MarketTransaction[] transactions) {
        this.transactions = transactions;
        return this;
    }
    
    public Market(@JsonProperty("exchange") TradeGood[] exchange, @JsonProperty("exports") TradeGood[] exports, @JsonProperty("imports") TradeGood[] imports, @JsonProperty("symbol") String symbol) {
        this.exchange = exchange;
        this.exports = exports;
        this.imports = imports;
        this.symbol = symbol;
  }
}
