/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MarketTradeGoodSupply - A rough estimate of the total supply of this good in the marketplace.
 */
public enum MarketTradeGoodSupply {
    SCARCE("SCARCE"),
    LIMITED("LIMITED"),
    MODERATE("MODERATE"),
    ABUNDANT("ABUNDANT");

    @JsonValue
    public final String value;

    private MarketTradeGoodSupply(String value) {
        this.value = value;
    }
}
