/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MarketTransactionType - The type of transaction.
 */
public enum MarketTransactionType {
    PURCHASE("PURCHASE"),
    SELL("SELL");

    @JsonValue
    public final String value;

    private MarketTransactionType(String value) {
        this.value = value;
    }
}
