/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class Meta {
    @JsonProperty("limit")
    public Long limit;

    public Meta withLimit(Long limit) {
        this.limit = limit;
        return this;
    }
    
    @JsonProperty("page")
    public Long page;

    public Meta withPage(Long page) {
        this.page = page;
        return this;
    }
    
    @JsonProperty("total")
    public Long total;

    public Meta withTotal(Long total) {
        this.total = total;
        return this;
    }
    
    public Meta(@JsonProperty("limit") Long limit, @JsonProperty("page") Long page, @JsonProperty("total") Long total) {
        this.limit = limit;
        this.page = page;
        this.total = total;
  }
}
