/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ScannedShipMounts - A mount on the ship.
 */
public class ScannedShipMounts {
    @JsonProperty("symbol")
    public String symbol;

    public ScannedShipMounts withSymbol(String symbol) {
        this.symbol = symbol;
        return this;
    }
    
    public ScannedShipMounts(@JsonProperty("symbol") String symbol) {
        this.symbol = symbol;
  }
}
