/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ScannedShipReactor - The reactor of the ship.
 */
public class ScannedShipReactor {
    @JsonProperty("symbol")
    public String symbol;

    public ScannedShipReactor withSymbol(String symbol) {
        this.symbol = symbol;
        return this;
    }
    
    public ScannedShipReactor(@JsonProperty("symbol") String symbol) {
        this.symbol = symbol;
  }
}
