/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ScannedShipEngine - The engine of the ship.
 */
public class ScannedShipEngine {
    @JsonProperty("symbol")
    public String symbol;

    public ScannedShipEngine withSymbol(String symbol) {
        this.symbol = symbol;
        return this;
    }
    
    public ScannedShipEngine(@JsonProperty("symbol") String symbol) {
        this.symbol = symbol;
  }
}
