/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class ScannedSystem {
    @JsonProperty("distance")
    public Long distance;

    public ScannedSystem withDistance(Long distance) {
        this.distance = distance;
        return this;
    }
    
    @JsonProperty("sectorSymbol")
    public String sectorSymbol;

    public ScannedSystem withSectorSymbol(String sectorSymbol) {
        this.sectorSymbol = sectorSymbol;
        return this;
    }
    
    @JsonProperty("symbol")
    public String symbol;

    public ScannedSystem withSymbol(String symbol) {
        this.symbol = symbol;
        return this;
    }
    
    /**
     * The type of waypoint.
     */
    @JsonProperty("type")
    public SystemType type;

    public ScannedSystem withType(SystemType type) {
        this.type = type;
        return this;
    }
    
    @JsonProperty("x")
    public Long x;

    public ScannedSystem withX(Long x) {
        this.x = x;
        return this;
    }
    
    @JsonProperty("y")
    public Long y;

    public ScannedSystem withY(Long y) {
        this.y = y;
        return this;
    }
    
    public ScannedSystem(@JsonProperty("distance") Long distance, @JsonProperty("sectorSymbol") String sectorSymbol, @JsonProperty("symbol") String symbol, @JsonProperty("type") SystemType type, @JsonProperty("x") Long x, @JsonProperty("y") Long y) {
        this.distance = distance;
        this.sectorSymbol = sectorSymbol;
        this.symbol = symbol;
        this.type = type;
        this.x = x;
        this.y = y;
  }
}
