/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ScannedShipFrame - The frame of the ship.
 */
public class ScannedShipFrame {
    @JsonProperty("symbol")
    public String symbol;

    public ScannedShipFrame withSymbol(String symbol) {
        this.symbol = symbol;
        return this;
    }
    
    public ScannedShipFrame(@JsonProperty("symbol") String symbol) {
        this.symbol = symbol;
  }
}
