/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ShipFrameSymbol {
    FRAME_PROBE("FRAME_PROBE"),
    FRAME_DRONE("FRAME_DRONE"),
    FRAME_INTERCEPTOR("FRAME_INTERCEPTOR"),
    FRAME_RACER("FRAME_RACER"),
    FRAME_FIGHTER("FRAME_FIGHTER"),
    FRAME_FRIGATE("FRAME_FRIGATE"),
    FRAME_SHUTTLE("FRAME_SHUTTLE"),
    FRAME_EXPLORER("FRAME_EXPLORER"),
    FRAME_MINER("FRAME_MINER"),
    FRAME_LIGHT_FREIGHTER("FRAME_LIGHT_FREIGHTER"),
    FRAME_HEAVY_FREIGHTER("FRAME_HEAVY_FREIGHTER"),
    FRAME_TRANSPORT("FRAME_TRANSPORT"),
    FRAME_DESTROYER("FRAME_DESTROYER"),
    FRAME_CRUISER("FRAME_CRUISER"),
    FRAME_CARRIER("FRAME_CARRIER");

    @JsonValue
    public final String value;

    private ShipFrameSymbol(String value) {
        this.value = value;
    }
}
