/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import emdash.SpaceTraders.utils.DateTimeDeserializer;
import emdash.SpaceTraders.utils.DateTimeSerializer;
import java.time.OffsetDateTime;

public class ShipFuelConsumed {
    /**
     * The amount of fuel consumed by the most recent transit or action.
     */
    @JsonProperty("amount")
    public Long amount;

    public ShipFuelConsumed withAmount(Long amount) {
        this.amount = amount;
        return this;
    }
    
    /**
     * The time at which the fuel was consumed.
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("timestamp")
    public OffsetDateTime timestamp;

    public ShipFuelConsumed withTimestamp(OffsetDateTime timestamp) {
        this.timestamp = timestamp;
        return this;
    }
    
    public ShipFuelConsumed(@JsonProperty("amount") Long amount, @JsonProperty("timestamp") OffsetDateTime timestamp) {
        this.amount = amount;
        this.timestamp = timestamp;
  }
}
