/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ShipType {
    SHIP_PROBE("SHIP_PROBE"),
    SHIP_MINING_DRONE("SHIP_MINING_DRONE"),
    SHIP_INTERCEPTOR("SHIP_INTERCEPTOR"),
    SHIP_LIGHT_HAULER("SHIP_LIGHT_HAULER"),
    SHIP_COMMAND_FRIGATE("SHIP_COMMAND_FRIGATE"),
    SHIP_EXPLORER("SHIP_EXPLORER"),
    SHIP_HEAVY_FREIGHTER("SHIP_HEAVY_FREIGHTER"),
    SHIP_LIGHT_SHUTTLE("SHIP_LIGHT_SHUTTLE"),
    SHIP_ORE_HOUND("SHIP_ORE_HOUND"),
    SHIP_REFINING_FREIGHTER("SHIP_REFINING_FREIGHTER");

    @JsonValue
    public final String value;

    private ShipType(String value) {
        this.value = value;
    }
}
