/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ShipEngine - The engine determines how quickly a ship travels between waypoints.
 */
public class ShipEngine {
    /**
     * Condition is a range of 0 to 100 where 0 is completely worn out and 100 is brand new.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("condition")
    public Long condition;

    public ShipEngine withCondition(Long condition) {
        this.condition = condition;
        return this;
    }
    
    @JsonProperty("description")
    public String description;

    public ShipEngine withDescription(String description) {
        this.description = description;
        return this;
    }
    
    @JsonProperty("name")
    public String name;

    public ShipEngine withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * The requirements for installation on a ship
     */
    @JsonProperty("requirements")
    public ShipRequirements requirements;

    public ShipEngine withRequirements(ShipRequirements requirements) {
        this.requirements = requirements;
        return this;
    }
    
    @JsonProperty("speed")
    public Long speed;

    public ShipEngine withSpeed(Long speed) {
        this.speed = speed;
        return this;
    }
    
    @JsonProperty("symbol")
    public ShipEngineSymbol symbol;

    public ShipEngine withSymbol(ShipEngineSymbol symbol) {
        this.symbol = symbol;
        return this;
    }
    
    public ShipEngine(@JsonProperty("description") String description, @JsonProperty("name") String name, @JsonProperty("requirements") ShipRequirements requirements, @JsonProperty("speed") Long speed, @JsonProperty("symbol") ShipEngineSymbol symbol) {
        this.description = description;
        this.name = name;
        this.requirements = requirements;
        this.speed = speed;
        this.symbol = symbol;
  }
}
