/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ShipRole - The registered role of the ship
 */
public enum ShipRole {
    FABRICATOR("FABRICATOR"),
    HARVESTER("HARVESTER"),
    HAULER("HAULER"),
    INTERCEPTOR("INTERCEPTOR"),
    EXCAVATOR("EXCAVATOR"),
    TRANSPORT("TRANSPORT"),
    REPAIR("REPAIR"),
    SURVEYOR("SURVEYOR"),
    COMMAND("COMMAND"),
    CARRIER("CARRIER"),
    PATROL("PATROL"),
    SATELLITE("SATELLITE"),
    EXPLORER("EXPLORER"),
    REFINERY("REFINERY");

    @JsonValue
    public final String value;

    private ShipRole(String value) {
        this.value = value;
    }
}
