/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ShipCrew - The ship's crew service and maintain the ship's systems and equipment.
 */
public class ShipCrew {
    /**
     * The maximum number of crew members the ship can support.
     */
    @JsonProperty("capacity")
    public Long capacity;

    public ShipCrew withCapacity(Long capacity) {
        this.capacity = capacity;
        return this;
    }
    
    /**
     * The current number of crew members on the ship.
     */
    @JsonProperty("current")
    public Long current;

    public ShipCrew withCurrent(Long current) {
        this.current = current;
        return this;
    }
    
    /**
     * A rough measure of the crew's morale. A higher morale means the crew is happier and more productive. A lower morale means the ship is more prone to accidents.
     */
    @JsonProperty("morale")
    public Long morale;

    public ShipCrew withMorale(Long morale) {
        this.morale = morale;
        return this;
    }
    
    /**
     * The minimum number of crew members required to maintain the ship.
     */
    @JsonProperty("required")
    public Long required;

    public ShipCrew withRequired(Long required) {
        this.required = required;
        return this;
    }
    
    /**
     * The rotation of crew shifts. A stricter shift improves the ship's performance. A more relaxed shift improves the crew's morale.
     */
    @JsonProperty("rotation")
    public ShipCrewRotation rotation;

    public ShipCrew withRotation(ShipCrewRotation rotation) {
        this.rotation = rotation;
        return this;
    }
    
    /**
     * The amount of credits per crew member paid per hour. Wages are paid when a ship docks at a civilized waypoint.
     */
    @JsonProperty("wages")
    public Long wages;

    public ShipCrew withWages(Long wages) {
        this.wages = wages;
        return this;
    }
    
    public ShipCrew(@JsonProperty("capacity") Long capacity, @JsonProperty("current") Long current, @JsonProperty("morale") Long morale, @JsonProperty("required") Long required, @JsonProperty("rotation") ShipCrewRotation rotation, @JsonProperty("wages") Long wages) {
        this.capacity = capacity;
        this.current = current;
        this.morale = morale;
        this.required = required;
        this.rotation = rotation;
        this.wages = wages;
  }
}
