/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ShipMount - A mount is installed on the exterier of a ship.
 */
public class ShipMount {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("deposits")
    public ShipMountDeposits[] deposits;

    public ShipMount withDeposits(ShipMountDeposits[] deposits) {
        this.deposits = deposits;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    public String description;

    public ShipMount withDescription(String description) {
        this.description = description;
        return this;
    }
    
    @JsonProperty("name")
    public String name;

    public ShipMount withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * The requirements for installation on a ship
     */
    @JsonProperty("requirements")
    public ShipRequirements requirements;

    public ShipMount withRequirements(ShipRequirements requirements) {
        this.requirements = requirements;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("strength")
    public Long strength;

    public ShipMount withStrength(Long strength) {
        this.strength = strength;
        return this;
    }
    
    @JsonProperty("symbol")
    public ShipMountSymbol symbol;

    public ShipMount withSymbol(ShipMountSymbol symbol) {
        this.symbol = symbol;
        return this;
    }
    
    public ShipMount(@JsonProperty("name") String name, @JsonProperty("requirements") ShipRequirements requirements, @JsonProperty("symbol") ShipMountSymbol symbol) {
        this.name = name;
        this.requirements = requirements;
        this.symbol = symbol;
  }
}
