/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ShipNavRouteWaypoint - The destination or departure of a ships nav route.
 */
public class ShipNavRouteWaypoint {
    @JsonProperty("symbol")
    public String symbol;

    public ShipNavRouteWaypoint withSymbol(String symbol) {
        this.symbol = symbol;
        return this;
    }
    
    @JsonProperty("systemSymbol")
    public String systemSymbol;

    public ShipNavRouteWaypoint withSystemSymbol(String systemSymbol) {
        this.systemSymbol = systemSymbol;
        return this;
    }
    
    /**
     * The type of waypoint.
     */
    @JsonProperty("type")
    public WaypointType type;

    public ShipNavRouteWaypoint withType(WaypointType type) {
        this.type = type;
        return this;
    }
    
    @JsonProperty("x")
    public Long x;

    public ShipNavRouteWaypoint withX(Long x) {
        this.x = x;
        return this;
    }
    
    @JsonProperty("y")
    public Long y;

    public ShipNavRouteWaypoint withY(Long y) {
        this.y = y;
        return this;
    }
    
    public ShipNavRouteWaypoint(@JsonProperty("symbol") String symbol, @JsonProperty("systemSymbol") String systemSymbol, @JsonProperty("type") WaypointType type, @JsonProperty("x") Long x, @JsonProperty("y") Long y) {
        this.symbol = symbol;
        this.systemSymbol = systemSymbol;
        this.type = type;
        this.x = x;
        this.y = y;
  }
}
