/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ShipRegistration - The public registration information of the ship
 */
public class ShipRegistration {
    /**
     * The symbol of the faction the ship is registered with
     */
    @JsonProperty("factionSymbol")
    public String factionSymbol;

    public ShipRegistration withFactionSymbol(String factionSymbol) {
        this.factionSymbol = factionSymbol;
        return this;
    }
    
    /**
     * The agent's registered name of the ship
     */
    @JsonProperty("name")
    public String name;

    public ShipRegistration withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * The registered role of the ship
     */
    @JsonProperty("role")
    public ShipRole role;

    public ShipRegistration withRole(ShipRole role) {
        this.role = role;
        return this;
    }
    
    public ShipRegistration(@JsonProperty("factionSymbol") String factionSymbol, @JsonProperty("name") String name, @JsonProperty("role") ShipRole role) {
        this.factionSymbol = factionSymbol;
        this.name = name;
        this.role = role;
  }
}
