/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ShipCargoItem - The type of cargo item and the number of units.
 */
public class ShipCargoItem {
    /**
     * The description of the cargo item type.
     */
    @JsonProperty("description")
    public String description;

    public ShipCargoItem withDescription(String description) {
        this.description = description;
        return this;
    }
    
    /**
     * The name of the cargo item type.
     */
    @JsonProperty("name")
    public String name;

    public ShipCargoItem withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * The unique identifier of the cargo item type.
     */
    @JsonProperty("symbol")
    public String symbol;

    public ShipCargoItem withSymbol(String symbol) {
        this.symbol = symbol;
        return this;
    }
    
    /**
     * The number of units of the cargo item.
     */
    @JsonProperty("units")
    public Long units;

    public ShipCargoItem withUnits(Long units) {
        this.units = units;
        return this;
    }
    
    public ShipCargoItem(@JsonProperty("description") String description, @JsonProperty("name") String name, @JsonProperty("symbol") String symbol, @JsonProperty("units") Long units) {
        this.description = description;
        this.name = name;
        this.symbol = symbol;
        this.units = units;
  }
}
