/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ShipMountDeposits {
    QUARTZ_SAND("QUARTZ_SAND"),
    SILICON_CRYSTALS("SILICON_CRYSTALS"),
    PRECIOUS_STONES("PRECIOUS_STONES"),
    ICE_WATER("ICE_WATER"),
    AMMONIA_ICE("AMMONIA_ICE"),
    IRON_ORE("IRON_ORE"),
    COPPER_ORE("COPPER_ORE"),
    SILVER_ORE("SILVER_ORE"),
    ALUMINUM_ORE("ALUMINUM_ORE"),
    GOLD_ORE("GOLD_ORE"),
    PLATINUM_ORE("PLATINUM_ORE"),
    DIAMONDS("DIAMONDS"),
    URANITE_ORE("URANITE_ORE"),
    MERITIUM_ORE("MERITIUM_ORE");

    @JsonValue
    public final String value;

    private ShipMountDeposits(String value) {
        this.value = value;
    }
}
