/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ShipNavStatus - The current status of the ship
 */
public enum ShipNavStatus {
    IN_TRANSIT("IN_TRANSIT"),
    IN_ORBIT("IN_ORBIT"),
    DOCKED("DOCKED");

    @JsonValue
    public final String value;

    private ShipNavStatus(String value) {
        this.value = value;
    }
}
