/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ShipFrame - The frame of the ship. The frame determines the number of modules and mounting points of the ship, as well as base fuel capacity. As the condition of the frame takes more wear, the ship will become more sluggish and less maneuverable.
 */
public class ShipFrame {
    /**
     * Condition is a range of 0 to 100 where 0 is completely worn out and 100 is brand new.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("condition")
    public Long condition;

    public ShipFrame withCondition(Long condition) {
        this.condition = condition;
        return this;
    }
    
    @JsonProperty("description")
    public String description;

    public ShipFrame withDescription(String description) {
        this.description = description;
        return this;
    }
    
    @JsonProperty("fuelCapacity")
    public Long fuelCapacity;

    public ShipFrame withFuelCapacity(Long fuelCapacity) {
        this.fuelCapacity = fuelCapacity;
        return this;
    }
    
    @JsonProperty("moduleSlots")
    public Long moduleSlots;

    public ShipFrame withModuleSlots(Long moduleSlots) {
        this.moduleSlots = moduleSlots;
        return this;
    }
    
    @JsonProperty("mountingPoints")
    public Long mountingPoints;

    public ShipFrame withMountingPoints(Long mountingPoints) {
        this.mountingPoints = mountingPoints;
        return this;
    }
    
    @JsonProperty("name")
    public String name;

    public ShipFrame withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * The requirements for installation on a ship
     */
    @JsonProperty("requirements")
    public ShipRequirements requirements;

    public ShipFrame withRequirements(ShipRequirements requirements) {
        this.requirements = requirements;
        return this;
    }
    
    @JsonProperty("symbol")
    public ShipFrameSymbol symbol;

    public ShipFrame withSymbol(ShipFrameSymbol symbol) {
        this.symbol = symbol;
        return this;
    }
    
    public ShipFrame(@JsonProperty("description") String description, @JsonProperty("fuelCapacity") Long fuelCapacity, @JsonProperty("moduleSlots") Long moduleSlots, @JsonProperty("mountingPoints") Long mountingPoints, @JsonProperty("name") String name, @JsonProperty("requirements") ShipRequirements requirements, @JsonProperty("symbol") ShipFrameSymbol symbol) {
        this.description = description;
        this.fuelCapacity = fuelCapacity;
        this.moduleSlots = moduleSlots;
        this.mountingPoints = mountingPoints;
        this.name = name;
        this.requirements = requirements;
        this.symbol = symbol;
  }
}
