/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ShipFuel - Details of the ship's fuel tanks including how much fuel was consumed during the last transit or action.
 */
public class ShipFuel {
    /**
     * The maximum amount of fuel the ship's tanks can hold.
     */
    @JsonProperty("capacity")
    public Long capacity;

    public ShipFuel withCapacity(Long capacity) {
        this.capacity = capacity;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("consumed")
    public ShipFuelConsumed consumed;

    public ShipFuel withConsumed(ShipFuelConsumed consumed) {
        this.consumed = consumed;
        return this;
    }
    
    /**
     * The current amount of fuel in the ship's tanks.
     */
    @JsonProperty("current")
    public Long current;

    public ShipFuel withCurrent(Long current) {
        this.current = current;
        return this;
    }
    
    public ShipFuel(@JsonProperty("capacity") Long capacity, @JsonProperty("current") Long current) {
        this.capacity = capacity;
        this.current = current;
  }
}
