/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class Shipyard {
    /**
     * The list of ship types available for purchase at this shipyard.
     */
    @JsonProperty("shipTypes")
    public ShipyardShipTypes[] shipTypes;

    public Shipyard withShipTypes(ShipyardShipTypes[] shipTypes) {
        this.shipTypes = shipTypes;
        return this;
    }
    
    /**
     * The ships that are currently available for purchase at the shipyard.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("ships")
    public ShipyardShip[] ships;

    public Shipyard withShips(ShipyardShip[] ships) {
        this.ships = ships;
        return this;
    }
    
    /**
     * The symbol of the shipyard. The symbol is the same as the waypoint where the shipyard is located.
     */
    @JsonProperty("symbol")
    public String symbol;

    public Shipyard withSymbol(String symbol) {
        this.symbol = symbol;
        return this;
    }
    
    /**
     * The list of recent transactions at this shipyard.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("transactions")
    public ShipyardTransaction[] transactions;

    public Shipyard withTransactions(ShipyardTransaction[] transactions) {
        this.transactions = transactions;
        return this;
    }
    
    public Shipyard(@JsonProperty("shipTypes") ShipyardShipTypes[] shipTypes, @JsonProperty("symbol") String symbol) {
        this.shipTypes = shipTypes;
        this.symbol = symbol;
  }
}
