/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ShipEngineSymbol {
    ENGINE_IMPULSE_DRIVE_I("ENGINE_IMPULSE_DRIVE_I"),
    ENGINE_ION_DRIVE_I("ENGINE_ION_DRIVE_I"),
    ENGINE_ION_DRIVE_II("ENGINE_ION_DRIVE_II"),
    ENGINE_HYPER_DRIVE_I("ENGINE_HYPER_DRIVE_I");

    @JsonValue
    public final String value;

    private ShipEngineSymbol(String value) {
        this.value = value;
    }
}
