/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class ShipCargo {
    /**
     * The max number of items that can be stored in the cargo hold.
     */
    @JsonProperty("capacity")
    public Long capacity;

    public ShipCargo withCapacity(Long capacity) {
        this.capacity = capacity;
        return this;
    }
    
    /**
     * The items currently in the cargo hold.
     */
    @JsonProperty("inventory")
    public ShipCargoItem[] inventory;

    public ShipCargo withInventory(ShipCargoItem[] inventory) {
        this.inventory = inventory;
        return this;
    }
    
    /**
     * The number of items currently stored in the cargo hold.
     */
    @JsonProperty("units")
    public Long units;

    public ShipCargo withUnits(Long units) {
        this.units = units;
        return this;
    }
    
    public ShipCargo(@JsonProperty("capacity") Long capacity, @JsonProperty("inventory") ShipCargoItem[] inventory, @JsonProperty("units") Long units) {
        this.capacity = capacity;
        this.inventory = inventory;
        this.units = units;
  }
}
