/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import emdash.SpaceTraders.utils.DateTimeDeserializer;
import emdash.SpaceTraders.utils.DateTimeSerializer;
import java.time.OffsetDateTime;

public class ShipyardTransaction {
    /**
     * The symbol of the agent that made the transaction.
     */
    @JsonProperty("agentSymbol")
    public String agentSymbol;

    public ShipyardTransaction withAgentSymbol(String agentSymbol) {
        this.agentSymbol = agentSymbol;
        return this;
    }
    
    /**
     * The price of the transaction.
     */
    @JsonProperty("price")
    public Long price;

    public ShipyardTransaction withPrice(Long price) {
        this.price = price;
        return this;
    }
    
    /**
     * The symbol of the ship that was purchased.
     */
    @JsonProperty("shipSymbol")
    public String shipSymbol;

    public ShipyardTransaction withShipSymbol(String shipSymbol) {
        this.shipSymbol = shipSymbol;
        return this;
    }
    
    /**
     * The timestamp of the transaction.
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("timestamp")
    public OffsetDateTime timestamp;

    public ShipyardTransaction withTimestamp(OffsetDateTime timestamp) {
        this.timestamp = timestamp;
        return this;
    }
    
    /**
     * The symbol of the waypoint where the transaction took place.
     */
    @JsonProperty("waypointSymbol")
    public String waypointSymbol;

    public ShipyardTransaction withWaypointSymbol(String waypointSymbol) {
        this.waypointSymbol = waypointSymbol;
        return this;
    }
    
    public ShipyardTransaction(@JsonProperty("agentSymbol") String agentSymbol, @JsonProperty("price") Long price, @JsonProperty("shipSymbol") String shipSymbol, @JsonProperty("timestamp") OffsetDateTime timestamp, @JsonProperty("waypointSymbol") String waypointSymbol) {
        this.agentSymbol = agentSymbol;
        this.price = price;
        this.shipSymbol = shipSymbol;
        this.timestamp = timestamp;
        this.waypointSymbol = waypointSymbol;
  }
}
