/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ShipNav - The navigation information of the ship.
 */
public class ShipNav {
    /**
     * The ship's set speed when traveling between waypoints or systems.
     */
    @JsonProperty("flightMode")
    public ShipNavFlightMode flightMode;

    public ShipNav withFlightMode(ShipNavFlightMode flightMode) {
        this.flightMode = flightMode;
        return this;
    }
    
    /**
     * The routing information for the ship's most recent transit or current location.
     */
    @JsonProperty("route")
    public ShipNavRoute route;

    public ShipNav withRoute(ShipNavRoute route) {
        this.route = route;
        return this;
    }
    
    /**
     * The current status of the ship
     */
    @JsonProperty("status")
    public ShipNavStatus status;

    public ShipNav withStatus(ShipNavStatus status) {
        this.status = status;
        return this;
    }
    
    /**
     * The system symbol of the ship's current location.
     */
    @JsonProperty("systemSymbol")
    public String systemSymbol;

    public ShipNav withSystemSymbol(String systemSymbol) {
        this.systemSymbol = systemSymbol;
        return this;
    }
    
    /**
     * The waypoint symbol of the ship's current location, or if the ship is in-transit, the waypoint symbol of the ship's destination.
     */
    @JsonProperty("waypointSymbol")
    public String waypointSymbol;

    public ShipNav withWaypointSymbol(String waypointSymbol) {
        this.waypointSymbol = waypointSymbol;
        return this;
    }
    
    public ShipNav(@JsonProperty("flightMode") ShipNavFlightMode flightMode, @JsonProperty("route") ShipNavRoute route, @JsonProperty("status") ShipNavStatus status, @JsonProperty("systemSymbol") String systemSymbol, @JsonProperty("waypointSymbol") String waypointSymbol) {
        this.flightMode = flightMode;
        this.route = route;
        this.status = status;
        this.systemSymbol = systemSymbol;
        this.waypointSymbol = waypointSymbol;
  }
}
