/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ShipyardShipTypes {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    public ShipType type;

    public ShipyardShipTypes withType(ShipType type) {
        this.type = type;
        return this;
    }
    
    public ShipyardShipTypes(){}
}
