/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ShipReactorSymbol {
    REACTOR_SOLAR_I("REACTOR_SOLAR_I"),
    REACTOR_FUSION_I("REACTOR_FUSION_I"),
    REACTOR_FISSION_I("REACTOR_FISSION_I"),
    REACTOR_CHEMICAL_I("REACTOR_CHEMICAL_I"),
    REACTOR_ANTIMATTER_I("REACTOR_ANTIMATTER_I");

    @JsonValue
    public final String value;

    private ShipReactorSymbol(String value) {
        this.value = value;
    }
}
