/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ShipRequirements - The requirements for installation on a ship
 */
public class ShipRequirements {
    /**
     * The number of crew required for operation.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("crew")
    public Long crew;

    public ShipRequirements withCrew(Long crew) {
        this.crew = crew;
        return this;
    }
    
    /**
     * The amount of power required from the reactor.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("power")
    public Long power;

    public ShipRequirements withPower(Long power) {
        this.power = power;
        return this;
    }
    
    /**
     * The number of module slots required for installation.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("slots")
    public Long slots;

    public ShipRequirements withSlots(Long slots) {
        this.slots = slots;
        return this;
    }
    
    public ShipRequirements(){}
}
