/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import emdash.SpaceTraders.utils.DateTimeDeserializer;
import emdash.SpaceTraders.utils.DateTimeSerializer;
import java.time.OffsetDateTime;

/**
 * ShipNavRoute - The routing information for the ship's most recent transit or current location.
 */
public class ShipNavRoute {
    /**
     * The date time of the ship's arrival. If the ship is in-transit, this is the expected time of arrival.
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("arrival")
    public OffsetDateTime arrival;

    public ShipNavRoute withArrival(OffsetDateTime arrival) {
        this.arrival = arrival;
        return this;
    }
    
    /**
     * The destination or departure of a ships nav route.
     */
    @JsonProperty("departure")
    public ShipNavRouteWaypoint departure;

    public ShipNavRoute withDeparture(ShipNavRouteWaypoint departure) {
        this.departure = departure;
        return this;
    }
    
    /**
     * The date time of the ship's departure.
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("departureTime")
    public OffsetDateTime departureTime;

    public ShipNavRoute withDepartureTime(OffsetDateTime departureTime) {
        this.departureTime = departureTime;
        return this;
    }
    
    /**
     * The destination or departure of a ships nav route.
     */
    @JsonProperty("destination")
    public ShipNavRouteWaypoint destination;

    public ShipNavRoute withDestination(ShipNavRouteWaypoint destination) {
        this.destination = destination;
        return this;
    }
    
    public ShipNavRoute(@JsonProperty("arrival") OffsetDateTime arrival, @JsonProperty("departure") ShipNavRouteWaypoint departure, @JsonProperty("departureTime") OffsetDateTime departureTime, @JsonProperty("destination") ShipNavRouteWaypoint destination) {
        this.arrival = arrival;
        this.departure = departure;
        this.departureTime = departureTime;
        this.destination = destination;
  }
}
