/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ShipNavFlightMode - The ship's set speed when traveling between waypoints or systems.
 */
public enum ShipNavFlightMode {
    DRIFT("DRIFT"),
    STEALTH("STEALTH"),
    CRUISE("CRUISE"),
    BURN("BURN");

    @JsonValue
    public final String value;

    private ShipNavFlightMode(String value) {
        this.value = value;
    }
}
