/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * SurveyDeposit - A surveyed deposit of a mineral or resource available for extraction.
 */
public class SurveyDeposit {
    /**
     * The symbol of the deposit.
     */
    @JsonProperty("symbol")
    public String symbol;

    public SurveyDeposit withSymbol(String symbol) {
        this.symbol = symbol;
        return this;
    }
    
    public SurveyDeposit(@JsonProperty("symbol") String symbol) {
        this.symbol = symbol;
  }
}
