/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SurveySize - The size of the deposit. This value indicates how much can be extracted from the survey before it is exhausted.
 */
public enum SurveySize {
    SMALL("SMALL"),
    MODERATE("MODERATE"),
    LARGE("LARGE");

    @JsonValue
    public final String value;

    private SurveySize(String value) {
        this.value = value;
    }
}
