/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class SystemFaction {
    @JsonProperty("symbol")
    public String symbol;

    public SystemFaction withSymbol(String symbol) {
        this.symbol = symbol;
        return this;
    }
    
    public SystemFaction(@JsonProperty("symbol") String symbol) {
        this.symbol = symbol;
  }
}
