/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class SystemWaypoint {
    @JsonProperty("symbol")
    public String symbol;

    public SystemWaypoint withSymbol(String symbol) {
        this.symbol = symbol;
        return this;
    }
    
    /**
     * The type of waypoint.
     */
    @JsonProperty("type")
    public WaypointType type;

    public SystemWaypoint withType(WaypointType type) {
        this.type = type;
        return this;
    }
    
    @JsonProperty("x")
    public Long x;

    public SystemWaypoint withX(Long x) {
        this.x = x;
        return this;
    }
    
    @JsonProperty("y")
    public Long y;

    public SystemWaypoint withY(Long y) {
        this.y = y;
        return this;
    }
    
    public SystemWaypoint(@JsonProperty("symbol") String symbol, @JsonProperty("type") WaypointType type, @JsonProperty("x") Long x, @JsonProperty("y") Long y) {
        this.symbol = symbol;
        this.type = type;
        this.x = x;
        this.y = y;
  }
}
