/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class System {
    @JsonProperty("factions")
    public SystemFaction[] factions;

    public System withFactions(SystemFaction[] factions) {
        this.factions = factions;
        return this;
    }
    
    @JsonProperty("sectorSymbol")
    public String sectorSymbol;

    public System withSectorSymbol(String sectorSymbol) {
        this.sectorSymbol = sectorSymbol;
        return this;
    }
    
    @JsonProperty("symbol")
    public String symbol;

    public System withSymbol(String symbol) {
        this.symbol = symbol;
        return this;
    }
    
    /**
     * The type of waypoint.
     */
    @JsonProperty("type")
    public SystemType type;

    public System withType(SystemType type) {
        this.type = type;
        return this;
    }
    
    @JsonProperty("waypoints")
    public SystemWaypoint[] waypoints;

    public System withWaypoints(SystemWaypoint[] waypoints) {
        this.waypoints = waypoints;
        return this;
    }
    
    @JsonProperty("x")
    public Long x;

    public System withX(Long x) {
        this.x = x;
        return this;
    }
    
    @JsonProperty("y")
    public Long y;

    public System withY(Long y) {
        this.y = y;
        return this;
    }
    
    public System(@JsonProperty("factions") SystemFaction[] factions, @JsonProperty("sectorSymbol") String sectorSymbol, @JsonProperty("symbol") String symbol, @JsonProperty("type") SystemType type, @JsonProperty("waypoints") SystemWaypoint[] waypoints, @JsonProperty("x") Long x, @JsonProperty("y") Long y) {
        this.factions = factions;
        this.sectorSymbol = sectorSymbol;
        this.symbol = symbol;
        this.type = type;
        this.waypoints = waypoints;
        this.x = x;
        this.y = y;
  }
}
