/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SystemType - The type of waypoint.
 */
public enum SystemType {
    NEUTRON_STAR("NEUTRON_STAR"),
    RED_STAR("RED_STAR"),
    ORANGE_STAR("ORANGE_STAR"),
    BLUE_STAR("BLUE_STAR"),
    YOUNG_STAR("YOUNG_STAR"),
    WHITE_DWARF("WHITE_DWARF"),
    BLACK_HOLE("BLACK_HOLE"),
    HYPERGIANT("HYPERGIANT"),
    NEBULA("NEBULA"),
    UNSTABLE("UNSTABLE");

    @JsonValue
    public final String value;

    private SystemType(String value) {
        this.value = value;
    }
}
