/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class TradeGood {
    @JsonProperty("description")
    public String description;

    public TradeGood withDescription(String description) {
        this.description = description;
        return this;
    }
    
    @JsonProperty("name")
    public String name;

    public TradeGood withName(String name) {
        this.name = name;
        return this;
    }
    
    @JsonProperty("symbol")
    public TradeSymbol symbol;

    public TradeGood withSymbol(TradeSymbol symbol) {
        this.symbol = symbol;
        return this;
    }
    
    public TradeGood(@JsonProperty("description") String description, @JsonProperty("name") String name, @JsonProperty("symbol") TradeSymbol symbol) {
        this.description = description;
        this.name = name;
        this.symbol = symbol;
  }
}
