/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * WaypointOrbital - An orbital is another waypoint that orbits a parent waypoint.
 */
public class WaypointOrbital {
    @JsonProperty("symbol")
    public String symbol;

    public WaypointOrbital withSymbol(String symbol) {
        this.symbol = symbol;
        return this;
    }
    
    public WaypointOrbital(@JsonProperty("symbol") String symbol) {
        this.symbol = symbol;
  }
}
