/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class WaypointTrait {
    /**
     * A description of the trait.
     */
    @JsonProperty("description")
    public String description;

    public WaypointTrait withDescription(String description) {
        this.description = description;
        return this;
    }
    
    /**
     * The name of the trait.
     */
    @JsonProperty("name")
    public String name;

    public WaypointTrait withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * The unique identifier of the trait.
     */
    @JsonProperty("symbol")
    public WaypointTraitSymbol symbol;

    public WaypointTrait withSymbol(WaypointTraitSymbol symbol) {
        this.symbol = symbol;
        return this;
    }
    
    public WaypointTrait(@JsonProperty("description") String description, @JsonProperty("name") String name, @JsonProperty("symbol") WaypointTraitSymbol symbol) {
        this.description = description;
        this.name = name;
        this.symbol = symbol;
  }
}
