/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package emdash.SpaceTraders.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * WaypointType - The type of waypoint.
 */
public enum WaypointType {
    PLANET("PLANET"),
    GAS_GIANT("GAS_GIANT"),
    MOON("MOON"),
    ORBITAL_STATION("ORBITAL_STATION"),
    JUMP_GATE("JUMP_GATE"),
    ASTEROID_FIELD("ASTEROID_FIELD"),
    NEBULA("NEBULA"),
    DEBRIS_FIELD("DEBRIS_FIELD"),
    GRAVITY_WELL("GRAVITY_WELL");

    @JsonValue
    public final String value;

    private WaypointType(String value) {
        this.value = value;
    }
}
